"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation"; import Link from "next/link";
const money=(v:any)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v)||0);
export default function EditCase({params}:{params:Promise<{id:string}>}){const router=useRouter();const [id,setId]=useState("");const [c,setC]=useState<any>(null);const [busy,setBusy]=useState(false);const [err,setErr]=useState("");const [name,setName]=useState("");const [data,setData]=useState<any>(null);const [meta,setMeta]=useState<any>({});
 useEffect(()=>{params.then(x=>{setId(x.id);fetch(`/api/cases/${x.id}`).then(r=>r.ok?r.json():null).then(v=>{if(!v){setErr("Dossier niet gevonden.");return;}setC(v);setName(v.name);setData(v.data||{});setMeta(v.metadata||{});}).catch(()=>setErr("Dossier laden mislukt."));});},[params]);
 const parent=(i:number)=>data?.parents?.[i]||{};
 const setP=(i:number,key:string,value:any)=>setData((d:any)=>({...d,parents:d.parents.map((p:any,j:number)=>j===i?({...p,[key]:value}):p)}));
 const setIncome=(i:number,key:string,value:any)=>setData((d:any)=>({...d,parents:d.parents.map((p:any,j:number)=>j===i?({...p,income:{...(p.income||{}),[key]:value}}):p)}));
 const setHousing=(i:number,key:string,value:any)=>setData((d:any)=>({...d,parents:d.parents.map((p:any,j:number)=>j===i?({...p,housing:{...(p.housing||{}),[key]:value}}):p)}));
 const setChild=(i:number,key:string,value:any)=>setData((d:any)=>({...d,children:d.children.map((x:any,j:number)=>j===i?({...x,[key]:value}):x)}));
 const num=(v:string)=>Number(String(v).replace(",","."))||0;
 async function save(){setBusy(true);setErr("");try{const r=await fetch(`/api/cases/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),clientId:c.clientId||undefined,data,meta})});if(!r.ok){setErr(await r.text());return;}router.push(`/cases/${id}`);router.refresh();}catch{setErr("Wijzigen en herberekenen mislukt.");}finally{setBusy(false);}}
 if(err&&!data)return <main className="content"><div className="notice error">{err}</div><Link className="btn secondary" href="/cases">Terug</Link></main>; if(!data)return <main className="content"><div className="panel">Dossier laden…</div></main>;
 const locked=c?.reviewStatus==="APPROVED"||c?.reviewStatus==="FINAL";
 if(locked)return <main className="content" style={{maxWidth:900}}><div className="page-head"><div><div className="eyebrow">Berekening vergrendeld</div><h1 className="page-title">{name}</h1><p className="page-subtitle">Deze berekening is {c.reviewStatus=== "FINAL"?"definitief":"goedgekeurd"} en kan niet rechtstreeks worden herberekend.</p></div></div><div className="notice error">Heropen eerst de review voordat je invoer wijzigt. Zo blijft de goedkeuringsprovenance intact en wordt een wijziging altijd als nieuwe berekeningssnapshot vastgelegd.</div><div className="actions topgap"><Link className="btn" href={`/cases/${id}/review`}>Naar review</Link><Link className="btn secondary" href={`/cases/${id}`}>Terug naar dossier</Link></div></main>;
 return <main className="content" style={{maxWidth:1220}}><div className="page-head"><div><div className="eyebrow">Bestaande berekening wijzigen</div><h1 className="page-title">{name}</h1><p className="page-subtitle">Pas de invoer aan en laat Alimenta de bestaande berekening opnieuw doorrekenen. Er wordt géén nieuw dossier aangemaakt.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link><button className="btn" disabled={busy} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button></div></div>{err&&<div className="notice error topgap">{err}</div>}
 <section className="panel topgap"><div className="section-kicker">Dossier</div><h2 className="panel-title">Algemene gegevens</h2><div className="form-grid topgap"><div><label className="label">Dossiernaam</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Ingangsdatum</label><input className="input" type="date" value={meta.effectiveDate||""} onChange={e=>setMeta((m:any)=>({...m,effectiveDate:e.target.value}))}/></div><div><label className="label">Scheidingsdatum</label><input className="input" type="date" value={meta.separationDate||""} onChange={e=>setMeta((m:any)=>({...m,separationDate:e.target.value}))}/></div><div className="full"><label className="label">Notitie</label><textarea className="input" rows={3} value={meta.notes||""} onChange={e=>setMeta((m:any)=>({...m,notes:e.target.value}))}/></div></div></section>
 <section className="panel topgap"><div className="section-kicker">Ouders</div><h2 className="panel-title">Inkomen, wonen en draagkracht</h2>{[0,1].map(i=><div className="form-card topgap" key={i}><div className="form-card-head"><h3>{parent(i).name||`Ouder ${i+1}`}</h3><span>Persoon {i===0?"A":"B"}</span></div><div className="form-grid"><div><label className="label">Naam</label><input className="input" value={parent(i).name||""} onChange={e=>setP(i,"name",e.target.value)}/></div><div><label className="label">NBI p/m</label><input className="input" inputMode="decimal" value={parent(i).nbi??""} onChange={e=>setP(i,"nbi",num(e.target.value))}/></div><div><label className="label">KGB p/m</label><input className="input" inputMode="decimal" value={parent(i).kgb??0} onChange={e=>setP(i,"kgb",num(e.target.value))}/></div><div><label className="label">Woonlasten p/m</label><input className="input" inputMode="decimal" value={parent(i).housing?.monthlyCosts??parent(i).housingCosts??0} onChange={e=>{setP(i,"housingCosts",num(e.target.value));setHousing(i,"monthlyCosts",num(e.target.value));}}/></div><div><label className="label">Woonvorm</label><select className="input" value={parent(i).housing?.type||"RENT"} onChange={e=>setHousing(i,"type",e.target.value)}><option value="RENT">Huurwoning</option><option value="OWNED">Eigen woning</option><option value="OTHER">Overig</option></select></div><div><label className="label">Bijzondere noodzakelijke kosten</label><input className="input" value={parent(i).specialNecessaryCosts??0} onChange={e=>setP(i,"specialNecessaryCosts",num(e.target.value))}/></div><div><label className="label">Overige onderhoudsverplichtingen</label><input className="input" value={parent(i).otherMaintenance??0} onChange={e=>setP(i,"otherMaintenance",num(e.target.value))}/></div>{parent(i).income?.mode&&<div><label className="label">Inkomensmodus</label><select className="input" value={parent(i).income.mode} onChange={e=>setIncome(i,"mode",e.target.value)}><option value="NBI">NBI</option><option value="NET">Netto</option><option value="GROSS">Bruto</option></select></div>}{parent(i).income?.mode==="GROSS"&&<div><label className="label">Bruto salaris p/m</label><input className="input" value={parent(i).income.salaryMonthly??0} onChange={e=>setIncome(i,"salaryMonthly",num(e.target.value))}/></div>}{parent(i).income?.mode==="NET"&&<div><label className="label">Netto inkomen p/m</label><input className="input" value={parent(i).income.netIncomeMonthly??0} onChange={e=>setIncome(i,"netIncomeMonthly",num(e.target.value))}/></div>}<div><label className="label">Zorgdagen p/week</label><input className="input" value={parent(i).careDaysPerWeek??0} onChange={e=>setP(i,"careDaysPerWeek",num(e.target.value))}/></div></div></div>)}</section>
 <section className="panel topgap"><div className="section-kicker">Kinderen</div><h2 className="panel-title">Kindgegevens</h2>{(data.children||[]).map((x:any,i:number)=><div className="form-card topgap" key={i}><div className="form-grid"><div><label className="label">Naam</label><input className="input" value={x.name||""} onChange={e=>setChild(i,"name",e.target.value)}/></div><div><label className="label">Leeftijd</label><input className="input" type="number" min="0" max="25" value={x.age??0} onChange={e=>setChild(i,"age",num(e.target.value))}/></div><div><label className="label">Hoofdverblijf</label><select className="input" value={x.residence||"A"} onChange={e=>setChild(i,"residence",e.target.value)}><option value="A">Ouder A</option><option value="B">Ouder B</option><option value="50-50">50/50</option></select></div><div><label className="label">Bijzondere kosten p/m</label><input className="input" value={x.specialCosts??0} onChange={e=>setChild(i,"specialCosts",num(e.target.value))}/></div><div><label className="label">Eigen inkomen p/m</label><input className="input" value={x.ownIncome??0} onChange={e=>setChild(i,"ownIncome",num(e.target.value))}/></div></div></div>)}</section>
 <section className="panel topgap"><div className="section-kicker">Partneralimentatie</div><h2 className="panel-title">PAL opnieuw berekenen</h2><div className="form-grid topgap">{data.partnerSupport&&<><div><label className="label">PAL-betaler</label><select className="input" value={data.partnerSupport.payerIndex??0} onChange={e=>setData((d:any)=>({...d,partnerSupport:{...d.partnerSupport,payerIndex:Number(e.target.value)}}))}><option value="0">Ouder A</option><option value="1">Ouder B</option></select></div><div><label className="label">Historisch NBGI p/m</label><input className="input" value={data.partnerSupport.historicalNBGI??data.historicalNBGI??0} onChange={e=>setData((d:any)=>({...d,historicalNBGI:num(e.target.value),partnerSupport:{...d.partnerSupport,historicalNBGI:num(e.target.value)}}))}/></div><div><label className="label">Historische kindkosten p/m</label><input className="input" value={data.partnerSupport.historicalChildCosts??0} onChange={e=>setData((d:any)=>({...d,partnerSupport:{...d.partnerSupport,historicalChildCosts:num(e.target.value)}}))}/></div><div><label className="label">Concrete need netto p/m</label><input className="input" value={data.partnerSupport.concreteNeedNet??0} onChange={e=>setData((d:any)=>({...d,partnerSupport:{...d.partnerSupport,concreteNeedNet:num(e.target.value)}}))}/></div></>}</div>{!data.partnerSupport&&<p className="panel-sub">Partneralimentatie is niet geconfigureerd voor dit dossier.</p>}</section>
 <div className="actions topgap"><button className="btn" disabled={busy} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link></div></main>}
