"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import Link from "next/link";
const n=(v:any)=>Number(String(v??"").replace(",","."))||0;
export default function EditCase({params}:{params:Promise<{id:string}>}){const router=useRouter();const[id,setId]=useState("");const[c,setC]=useState<any>();const[data,setData]=useState<any>();const[meta,setMeta]=useState<any>({});const[name,setName]=useState("");const[json,setJson]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{params.then(x=>{setId(x.id);fetch(`/api/cases/${x.id}`).then(r=>r.ok?r.json():null).then(v=>{if(!v){setErr("Dossier niet gevonden.");return}setC(v);setName(v.name);setData(v.data||{});setMeta(v.metadata||{});setJson(JSON.stringify(v.data||{},null,2))}).catch(()=>setErr("Dossier laden mislukt."))})},[params]);
 const p=(i:number)=>data?.parents?.[i]||{};const setP=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:d.parents.map((x:any,j:number)=>j===i?{...x,[k]:v}:x)}));const setI=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:d.parents.map((x:any,j:number)=>j===i?{...x,income:{...(x.income||{}),[k]:v}:x)}));
 async function save(){setBusy(true);setErr("");try{let finalData=data;try{finalData=JSON.parse(json)}catch{setErr("De geavanceerde invoer bevat ongeldige JSON.");setBusy(false);return}const r=await fetch(`/api/cases/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),clientId:c.clientId||undefined,data:finalData,meta})});if(!r.ok){setErr(await r.text());return}router.push(`/cases/${id}`);router.refresh()}catch{setErr("Wijzigen en herberekenen mislukt.")}finally{setBusy(false)}}
 if(err&&!data)return <main className="content"><div className="notice error">{err}</div><Link className="btn secondary" href="/cases">Terug</Link></main>;if(!data)return <main className="content"><div className="panel">Dossier laden…</div></main>;
 const locked=c?.reviewStatus==="APPROVED"||c?.reviewStatus==="FINAL";if(locked)return <main className="content" style={{maxWidth:900}}><div className="page-head"><div><div className="eyebrow">Berekening vergrendeld</div><h1 className="page-title">{name}</h1><p className="page-subtitle">Deze berekening is {c.reviewStatus==="FINAL"?"definitief":"goedgekeurd"} en kan niet rechtstreeks worden herberekend.</p></div></div><div className="notice error">Heropen eerst de review. Daarna kan de invoer worden gewijzigd en als nieuwe berekeningssnapshot worden opgeslagen.</div><div className="actions topgap"><Link className="btn" href={`/cases/${id}/review`}>Naar review</Link><Link className="btn secondary" href={`/cases/${id}`}>Terug</Link></div></main>;
 return <main className="content" style={{maxWidth:1220}}><div className="page-head"><div><div className="eyebrow">Bestaande berekening wijzigen</div><h1 className="page-title">{name}</h1><p className="page-subtitle">Wijzig de berekening binnen hetzelfde dossier. De volledige bestaande datastructuur blijft beschikbaar en kan desgewenst geavanceerd worden aangepast.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link><button className="btn" disabled={busy} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button></div></div>{err&&<div className="notice error topgap">{err}</div>}
 <section className="panel topgap"><div className="section-kicker">Snelle bewerking</div><h2 className="panel-title">Meest gebruikte gegevens</h2><div className="form-grid topgap"><div><label className="label">Dossiernaam</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Ingangsdatum</label><input className="input" type="date" value={meta.effectiveDate||""} onChange={e=>setMeta((m:any)=>({...m,effectiveDate:e.target.value}))}/></div><div><label className="label">Scheidingsdatum</label><input className="input" type="date" value={meta.separationDate||""} onChange={e=>setMeta((m:any)=>({...m,separationDate:e.target.value}))}/></div><div><label className="label">Vermogen ouder A</label><input className="input" value={meta.assetsA||0} onChange={e=>setMeta((m:any)=>({...m,assetsA:n(e.target.value)}))}/></div><div><label className="label">Vermogen ouder B</label><input className="input" value={meta.assetsB||0} onChange={e=>setMeta((m:any)=>({...m,assetsB:n(e.target.value)}))}/></div><div className="full"><label className="label">Notitie</label><textarea className="input" rows={3} value={meta.notes||""} onChange={e=>setMeta((m:any)=>({...m,notes:e.target.value}))}/></div></div></section>
 <section className="panel topgap"><div className="section-kicker">Ouders</div><h2 className="panel-title">Kerngegevens ouders</h2><div className="detail-grid">{[0,1].map(i=>{const x=p(i),inc=x.income||{};return <div className="detail-card" key={i}><h3>{x.name||`Ouder ${i+1}`}</h3><div className="form-grid topgap"><div><label className="label">Naam</label><input className="input" value={x.name||""} onChange={e=>setP(i,"name",e.target.value)}/></div><div><label className="label">NBI p/m</label><input className="input" value={x.nbi||0} onChange={e=>setP(i,"nbi",n(e.target.value))}/></div><div><label className="label">KGB p/m</label><input className="input" value={x.kgb||0} onChange={e=>setP(i,"kgb",n(e.target.value))}/></div><div><label className="label">Zorgdagen p/week</label><input className="input" value={x.careDaysPerWeek||0} onChange={e=>setP(i,"careDaysPerWeek",n(e.target.value))}/></div><div><label className="label">Woonlasten p/m</label><input className="input" value={x.housing?.monthlyCosts??x.housingCosts??0} onChange={e=>{setP(i,"housingCosts",n(e.target.value));setData((d:any)=>({...d,parents:d.parents.map((z:any,j:number)=>j===i?{...z,housing:{...(z.housing||{}),monthlyCosts:n(e.target.value)}}:z)}))}}/></div><div><label className="label">Bruto salaris p/m</label><input className="input" value={inc.salaryMonthly||0} onChange={e=>setI(i,"salaryMonthly",n(e.target.value))}/></div></div></div>})}</div></section>
 <section className="panel topgap"><div className="section-kicker">Volledige berekeningsinvoer</div><h2 className="panel-title">Geavanceerde gegevens</h2><p className="panel-sub">Hiermee zijn ook alle velden uit de berekeningswizard beschikbaar, inclusief inkomenscomponenten, woninggegevens, nieuwe partners, kindgegevens en PAL-parameters. Bestaande velden die niet in de snelle bewerking staan blijven behouden.</p><textarea className="input topgap" rows={30} value={json} onChange={e=>setJson(e.target.value)} spellCheck={false} style={{width:"100%",boxSizing:"border-box",fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace",fontSize:13}}/><div className="notice topgap">De invoer wordt vóór opslag gevalideerd door dezelfde berekeningsschema's als een nieuwe berekening. Opslaan maakt geen nieuw dossier.</div></section>
 <div className="actions topgap"><button className="btn" disabled={busy} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link></div></main>;
}