"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

const n=(v:any)=>Number(String(v??"").replace(",","."))||0;
const Field=({label,value,onChange,type="number",disabled=false}:{label:string;value:any;onChange:(v:any)=>void;type?:string;disabled?:boolean})=><div><label className="label">{label}</label><input className="input" disabled={disabled} type={type} value={value??""} onChange={e=>onChange(type==="number"?n(e.target.value):e.target.value)}/></div>;

export default function EditWizard({params}:{params:Promise<{id:string}>}){
 const router=useRouter();const[id,setId]=useState("");const[data,setData]=useState<any>(null);const[meta,setMeta]=useState<any>({});const[name,setName]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);const[reviewStatus,setReviewStatus]=useState<string>("INCOMPLETE");
 useEffect(()=>{params.then(x=>{setId(x.id);fetch(`/api/cases/${x.id}`).then(r=>r.ok?r.json():null).then(v=>{if(!v){setErr("Dossier niet gevonden.");return}setName(v.name);setData(v.data||{});setMeta(v.metadata||{});setReviewStatus(v.reviewStatus||"INCOMPLETE");}).catch(()=>setErr("Dossier laden mislukt."))})},[params]);
 const locked=reviewStatus==="APPROVED"||reviewStatus==="FINAL";
 const setRoot=(k:string,v:any)=>setData((d:any)=>({...d,[k]:v}));
 const setParent=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:(d.parents||[]).map((p:any,j:number)=>j===i?{...p,[k]:v}:p)}));
 const setIncome=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:(d.parents||[]).map((p:any,j:number)=>j===i?{...p,income:{...(p.income||{}),[k]:v}}:p)}));
 const setHousing=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:(d.parents||[]).map((p:any,j:number)=>j===i?{...p,housing:{...(p.housing||{}),[k]:v},housingCosts:k==="monthlyCosts"?v:p.housingCosts}:p)}));
 const setPartner=(i:number,k:string,v:any)=>setData((d:any)=>({...d,parents:(d.parents||[]).map((p:any,j:number)=>j===i?{...p,newPartner:{...(p.newPartner||{}),[k]:v}}:p)}));
 const setChild=(i:number,k:string,v:any)=>setData((d:any)=>({...d,children:(d.children||[]).map((c:any,j:number)=>j===i?{...c,[k]:v}:c)}));
 async function save(){if(locked)return;setBusy(true);setErr("");try{const r=await fetch(`/api/cases/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),data,meta})});if(!r.ok){setErr(await r.text());return}router.push(`/cases/${id}`);router.refresh()}catch{setErr("Wijzigen en herberekenen mislukt.")}finally{setBusy(false)}}
 if(err&&!data)return <main className="content"><div className="notice error">{err}</div><Link className="btn secondary" href="/cases">Terug</Link></main>;
 if(!data)return <main className="content"><div className="panel">Dossier laden…</div></main>;
 const disabled=locked||busy;
 return <main className="content" style={{maxWidth:1220}}><div className="page-head"><div><div className="eyebrow">Professionele wijzigingswizard</div><h1 className="page-title">{name}</h1><p className="page-subtitle">Wijzig bestaande berekeningsgegevens per onderdeel. Opslaan maakt binnen hetzelfde dossier een nieuwe immutable berekeningssnapshot.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link><button className="btn" disabled={disabled} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button></div></div>
 {locked&&<div className="notice topgap">Dit dossier is <strong>{reviewStatus}</strong> en daarom vergrendeld voor wijzigingen. Open eerst de workflow/review om het dossier opnieuw te beoordelen.</div>}
 {err&&<div className="notice error topgap">{err}</div>}
 <section className="panel topgap"><div className="section-kicker">Dossier</div><h2 className="panel-title">Algemene gegevens</h2><div className="form-grid topgap"><Field disabled={disabled} label="Dossiernaam" type="text" value={name} onChange={setName}/><Field disabled={disabled} label="Ingangsdatum" type="date" value={meta.effectiveDate||""} onChange={(v)=>setMeta((m:any)=>({...m,effectiveDate:v}))}/><Field disabled={disabled} label="Scheidingsdatum" type="date" value={meta.separationDate||""} onChange={(v)=>setMeta((m:any)=>({...m,separationDate:v}))}/><Field disabled={disabled} label="Vermogen ouder A" value={meta.assetsA||0} onChange={(v)=>setMeta((m:any)=>({...m,assetsA:v}))}/><Field disabled={disabled} label="Vermogen ouder B" value={meta.assetsB||0} onChange={(v)=>setMeta((m:any)=>({...m,assetsB:v}))}/><div className="full"><label className="label">Interne notitie</label><textarea disabled={disabled} className="input" rows={3} value={meta.notes||""} onChange={e=>setMeta((m:any)=>({...m,notes:e.target.value}))}/></div></div></section>
 <section className="panel topgap"><div className="section-kicker">Inkomen & draagkracht</div><h2 className="panel-title">Beide ouders</h2>{(data.parents||[]).map((p:any,i:number)=>{const inc=p.income||{};return <div className="form-card topgap" key={i}><div className="form-card-head"><div><h3>{p.name||`Ouder ${i+1}`}</h3><span>Persoon {i===0?"A":"B"}</span></div></div><div className="form-grid"><Field disabled={disabled} label="Naam" type="text" value={p.name||""} onChange={v=>setParent(i,"name",v)}/><div><label className="label">Inkomensmethode</label><select disabled={disabled} className="input" value={inc.mode||"NBI"} onChange={e=>setIncome(i,"mode",e.target.value)}><option value="GROSS">Bruto → NBI</option><option value="NET">Netto inkomen</option><option value="NBI">NBI rechtstreeks</option></select></div><Field disabled={disabled} label="NBI p/m" value={p.nbi||0} onChange={v=>setParent(i,"nbi",v)}/><Field disabled={disabled} label="Bruto salaris p/m" value={inc.salaryMonthly||0} onChange={v=>setIncome(i,"salaryMonthly",v)}/><Field disabled={disabled} label="Vakantietoeslag %" value={inc.holidayAllowancePct??8} onChange={v=>setIncome(i,"holidayAllowancePct",v)}/><Field disabled={disabled} label="IKB / PKB p/m" value={inc.ikbMonthly||0} onChange={v=>setIncome(i,"ikbMonthly",v)}/><Field disabled={disabled} label="Pensioenpremie p/m" value={inc.pensionMonthly||0} onChange={v=>setIncome(i,"pensionMonthly",v)}/><Field disabled={disabled} label="Overwerk p/m" value={inc.overtimeMonthly||0} onChange={v=>setIncome(i,"overtimeMonthly",v)}/><Field disabled={disabled} label="Bonus p/j" value={inc.bonusAnnual||0} onChange={v=>setIncome(i,"bonusAnnual",v)}/><Field disabled={disabled} label="KGB p/m" value={p.kgb||0} onChange={v=>setParent(i,"kgb",v)}/><Field disabled={disabled} label="Zorgdagen p/week" value={p.careDaysPerWeek||0} onChange={v=>setParent(i,"careDaysPerWeek",v)}/></div></div>})}</section>
 <section className="panel topgap"><div className="section-kicker">Wonen</div><h2 className="panel-title">Woning & woonlasten</h2>{(data.parents||[]).map((p:any,i:number)=>{const h=p.housing||{};return <div className="form-card topgap" key={i}><h3>{p.name||`Ouder ${i+1}`}</h3><div className="form-grid"><div><label className="label">Woonvorm</label><select disabled={disabled} className="input" value={h.type||"RENT"} onChange={e=>setHousing(i,"type",e.target.value)}><option value="RENT">Huurwoning</option><option value="OWNED">Eigen woning</option><option value="OTHER">Overig</option></select></div><Field disabled={disabled} label="Woonlasten p/m" value={h.monthlyCosts??p.housingCosts??0} onChange={v=>setHousing(i,"monthlyCosts",v)}/><Field disabled={disabled} label="Hypotheekrente p/m" value={h.mortgageInterestMonthly||0} onChange={v=>setHousing(i,"mortgageInterestMonthly",v)}/><Field disabled={disabled} label="Aflossing p/m" value={h.mortgagePrincipalMonthly||0} onChange={v=>setHousing(i,"mortgagePrincipalMonthly",v)}/><Field disabled={disabled} label="Woningwaarde" value={h.homeValue||0} onChange={v=>setHousing(i,"homeValue",v)}/><Field disabled={disabled} label="Hypotheekschuld" value={h.mortgageBalance||0} onChange={v=>setHousing(i,"mortgageBalance",v)}/><Field disabled={disabled} label="Fiscale renteaftrek p/m" value={h.mortgageInterestTaxBenefitMonthly||0} onChange={v=>setHousing(i,"mortgageInterestTaxBenefitMonthly",v)}/></div></div>})}</section>
 <section className="panel topgap"><div className="section-kicker">Nieuwe partner</div><h2 className="panel-title">Gezinssamenstelling</h2>{(data.parents||[]).map((p:any,i:number)=>{const np=p.newPartner||{};return <div className="form-card topgap" key={i}><h3>{p.name||`Ouder ${i+1}`}</h3><div className="form-grid"><label className="toggle-row"><input disabled={disabled} type="checkbox" checked={!!np.present} onChange={e=>setPartner(i,"present",e.target.checked)}/> Nieuwe partner aanwezig</label>{np.present&&<><Field disabled={disabled} label="Naam partner" type="text" value={np.name||""} onChange={v=>setPartner(i,"name",v)}/><Field disabled={disabled} label="NBI partner p/m" value={np.nbiMonthly||0} onChange={v=>setPartner(i,"nbiMonthly",v)}/><label className="toggle-row"><input disabled={disabled} type="checkbox" checked={np.selfSupporting!==false} onChange={e=>setPartner(i,"selfSupporting",e.target.checked)}/> Zelfredzaam</label></>}</div></div>})}</section>
 <section className="panel topgap"><div className="section-kicker">Kinderen</div><h2 className="panel-title">Kindgegevens</h2>{(data.children||[]).map((c:any,i:number)=><div className="form-card topgap" key={i}><div className="form-grid"><Field disabled={disabled} label="Naam" type="text" value={c.name||""} onChange={v=>setChild(i,"name",v)}/><Field disabled={disabled} label="Leeftijd" value={c.age||0} onChange={v=>setChild(i,"age",v)}/><div><label className="label">Hoofdverblijf</label><select disabled={disabled} className="input" value={c.residence||"A"} onChange={e=>setChild(i,"residence",e.target.value)}><option>A</option><option>B</option><option>50-50</option></select></div><Field disabled={disabled} label="Bijzondere kosten p/m" value={c.specialCosts||0} onChange={v=>setChild(i,"specialCosts",v)}/><Field disabled={disabled} label="Eigen inkomen p/m" value={c.ownIncome||0} onChange={v=>setChild(i,"ownIncome",v)}/></div></div>)}</section>
 <section className="panel topgap"><div className="section-kicker">Partneralimentatie</div><h2 className="panel-title">PAL-instellingen</h2><div className="form-grid"><label className="toggle-row"><input disabled={disabled} type="checkbox" checked={!!data.partnerSupport?.enabled} onChange={e=>setRoot("partnerSupport",{...(data.partnerSupport||{}),enabled:e.target.checked})}/> Partneralimentatie actief</label><div><label className="label">Betaler</label><select disabled={disabled} className="input" value={data.partnerSupport?.payerIndex??0} onChange={e=>setRoot("partnerSupport",{...(data.partnerSupport||{}),payerIndex:Number(e.target.value)})}><option value="0">Ouder A</option><option value="1">Ouder B</option></select></div><Field disabled={disabled} label="Historisch NBGI p/m" value={data.partnerSupport?.historicalNBGI||data.historicalNBGI||0} onChange={v=>setRoot("partnerSupport",{...(data.partnerSupport||{}),historicalNBGI:v})}/><Field disabled={disabled} label="Historische kindkosten p/m" value={data.partnerSupport?.historicalChildCosts||0} onChange={v=>setRoot("partnerSupport",{...(data.partnerSupport||{}),historicalChildCosts:v})}/><Field disabled={disabled} label="Concrete netto behoefte p/m" value={data.partnerSupport?.concreteNeedNet||0} onChange={v=>setRoot("partnerSupport",{...(data.partnerSupport||{}),concreteNeedNet:v})}/><Field disabled={disabled} label="Verdiencapaciteit ontvanger p/m" value={data.partnerSupport?.recipientVerdiencapaciteit||0} onChange={v=>setRoot("partnerSupport",{...(data.partnerSupport||{}),recipientVerdiencapaciteit:v})}/><Field disabled={disabled} label="Overige inkomsten ontvanger p/m" value={data.partnerSupport?.recipientOtherIncomeMonthly||0} onChange={v=>setRoot("partnerSupport",{...(data.partnerSupport||{}),recipientOtherIncomeMonthly:v})}/></div></section>
 <div className="actions topgap"><button className="btn" disabled={disabled} onClick={save}>{busy?"Herberekenen…":"Opslaan & herberekenen"}</button><Link className="btn secondary" href={`/cases/${id}`}>Annuleren</Link></div></main>;
}
