import Link from "next/link";
import AppShell from "@/components/AppShell";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { reviewCase, type ReviewSeverity } from "@/lib/case-review";
import { buildCalculationDifference } from "@/lib/calculation-difference";
import { buildReviewCalculationBinding, isReviewBindingCurrent } from "@/lib/review-binding";
import { buildProfessionalReviewState } from "@/lib/professional-review";

const labels: Record<ReviewSeverity, string> = { CRITICAL: "Kritiek", WARNING: "Controleren", INFO: "Aandacht", OK: "OK" };
const cls: Record<ReviewSeverity, string> = { CRITICAL: "red", WARNING: "amber", INFO: "gray", OK: "green" };
const date = (v: any) => new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v));
const money = (v: any) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(v) || 0);
const delta = (v: number) => v > 0 ? `+${money(v)}` : money(v);

export default async function ReviewPage({ params }: { params: Promise<{ id: string }> }) {
  const u = await requireUser();
  const { id } = await params;
  const c = await db.case.findFirst({ where: { id, userId: u.id }, include: { documents: { select: { aiStatus: true, approvedAt: true } }, calculations: { orderBy: { createdAt: "desc" }, take: 2 }, overrides: { orderBy: { createdAt: "desc" }, take: 50 } } });
  if (!c) return <AppShell><div className="notice error">Dossier niet gevonden.</div></AppShell>;
  const review = reviewCase({ data: c.data, documents: c.documents, calculations: c.calculations, result: c.result });
  const current = c.calculations[0];
  const previous = c.calculations[1];
  const difference = current && previous ? buildCalculationDifference({ previous: { inputSnapshot: previous.inputSnapshot, result: previous.result, fingerprint: (previous.result as any)?.calculationFingerprint || null }, current: { inputSnapshot: current.inputSnapshot, result: current.result, fingerprint: (current.result as any)?.calculationFingerprint || null } }) : null;
  const logs = await db.auditLog.findMany({ where: { userId: u.id, action: { in: ["CASE_REVIEW_COMMENTED", "CASE_REVIEW_STARTED", "CASE_READY_FOR_REVIEW", "CASE_REVIEWED", "CASE_APPROVED", "CASE_FINAL", "CASE_REOPENED", "CASE_REVIEW_CHECKED"] } }, orderBy: { createdAt: "desc" }, take: 200 });
  const history = logs.filter(x => String((x.metadata as any)?.caseId || "") === id);
  const professionalReview = buildProfessionalReviewState(history.filter(x => x.action === "CASE_REVIEW_CHECKED"), current?.id);
  const latestApprovalAudit = history.find(x => x.action === "CASE_APPROVED");
  const approvalBinding = latestApprovalAudit?.metadata && typeof latestApprovalAudit.metadata === "object" ? (latestApprovalAudit.metadata as Record<string, unknown>).calculationBinding as ReturnType<typeof buildReviewCalculationBinding> | undefined : undefined;
  const currentBinding = current ? buildReviewCalculationBinding({ id: current.id, engineVersion: current.engineVersion, normVersion: current.normVersion, result: current.result }) : null;
  const reportProvenanceCurrent = !!currentBinding && isReviewBindingCurrent(approvalBinding, currentBinding);
  const canMarkReady = c.reviewStatus === "INCOMPLETE" && review.readyForProfessionalReview;
  const canReview = c.reviewStatus === "READY_FOR_REVIEW" && professionalReview.complete;
  const canApprove = c.reviewStatus === "REVIEWED" && professionalReview.complete;
  const canFinalise = c.reviewStatus === "APPROVED" && professionalReview.complete;
  const canReopen = c.reviewStatus === "APPROVED" || c.reviewStatus === "FINAL";
  const result: any = c.result || {};
  const overrideOptions = [
    ["combined.childSupportTotal", "Totale kinderalimentatie", result.combined?.childSupportTotal],
    ["combined.partnerSupport.monthlyNet", "PAL netto", result.combined?.partnerSupport?.monthlyNet],
    ["combined.partnerSupport.monthlyGross", "PAL bruto", result.combined?.partnerSupport?.monthlyGross],
    ["combined.totalMonthlyPayments", "Totale maandelijkse betalingen", result.combined?.totalMonthlyPayments],
  ] as const;

  return <AppShell>
    <div className="page-head"><div><div className="eyebrow">Professionele review · grote fase</div><h1 className="page-title">{c.name}</h1><p className="page-subtitle">Van automatische signalering naar aantoonbare professionele controle, afwijking, herberekening en goedkeuring.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>← Dossier</Link><Link className="btn secondary" href={`/cases/${id}/edit/wizard`}>Wijzigen</Link><Link className="btn secondary" href={`/cases/${id}/history`}>Historie</Link></div></div>

    <div className="result-hero">
      <div className="stat-card result-main"><div className="stat-label">CASE REVIEW SCORE</div><div className="stat-value">{review.score}%</div><div className="stat-meta">{review.readyForProfessionalReview ? "Geen kritieke blokkade" : "Kritieke controlepunten aanwezig"}</div></div>
      <div className="stat-card"><div className="stat-label">KRITIEK</div><div className="stat-value">{review.criticalCount}</div><div className="stat-meta">Moet eerst worden opgelost</div></div>
      <div className="stat-card"><div className="stat-label">CHECKLIST</div><div className="stat-value">{professionalReview.checkedCount}/{professionalReview.totalCount}</div><div className="stat-meta">Professioneel gecontroleerd</div></div>
      <div className="stat-card"><div className="stat-label">STATUS</div><div className="stat-value" style={{fontSize:"18px"}}>{c.reviewStatus}</div><div className="stat-meta">Laatste workflowstatus</div></div>
    </div>

    <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">1–10 · Professioneel reviewcentrum</h2><div className="panel-sub">Iedere controle wordt aan de actuele calculation snapshot gekoppeld. Een nieuwe berekening maakt automatisch een nieuwe checklist.</div></div><span className={`status ${professionalReview.complete ? "green" : "amber"}`}>{professionalReview.complete ? "COMPLEET" : "INCOMPLEET"}</span></div>
      <div className="detail-grid topgap">{professionalReview.sections.map(section => <div className="detail-card" key={section.key}><div className="detail-card-head"><b>{section.label}</b><span className={`status ${section.checked ? "green" : "amber"}`}>{section.checked ? "Gecontroleerd" : "Open"}</span></div><div className="subtle">{section.description}</div><form className="topgap" action={`/api/cases/${id}/review/check`} method="post"><input type="hidden" name="section" value={section.key}/><button className="btn secondary" type="submit" disabled={c.reviewStatus === "APPROVED" || c.reviewStatus === "FINAL"}>{section.checked ? "Opnieuw bevestigen" : "Markeer gecontroleerd"}</button></form></div>)}</div>
      <div className="notice topgap">{professionalReview.complete ? "Alle professionele controleonderdelen zijn voor deze snapshot vastgelegd." : `Nog ${professionalReview.totalCount - professionalReview.checkedCount} controleonderdeel/onderdelen open. REVIEWED, APPROVED en FINAL worden server-side geblokkeerd totdat alles is gecontroleerd.`}</div>
    </section>

    <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Automatische signalering</h2><div className="panel-sub">Alimenta Pro signaleert; de professional beslist en legt de controle vast.</div></div></div>{review.items.map(item => <div className="review-row" key={item.key}><div className="review-icon">{item.severity === "OK" ? "✓" : item.severity === "CRITICAL" ? "!" : "•"}</div><div className="review-copy"><div className="review-title"><b>{item.title}</b><span className={`status ${cls[item.severity]}`}>{labels[item.severity]}</span></div><div className="subtle">{item.detail}</div>{item.action && <div className="review-action">Volgende stap: {item.action}</div>}</div></div>)}</section>

    {difference && <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Berekeningscontrole</h2><div className="panel-sub">Financiële delta's en gewijzigde invoer sinds de vorige immutable snapshot.</div></div><Link className="btn ghost" href={`/cases/${id}/history/compare/${previous!.id}/${current!.id}`}>Volledige vergelijking</Link></div><div className="result-overview"><div className="result-metric"><div className="stat-label">KINDERALIMENTATIE</div><div className="metric-value">{delta(difference.delta.childSupport)}</div><span>verschil p/m</span></div><div className="result-metric"><div className="stat-label">PAL NETTO</div><div className="metric-value">{delta(difference.delta.partnerSupportNet)}</div><span>verschil p/m</span></div><div className="result-metric"><div className="stat-label">PAL BRUTO</div><div className="metric-value">{delta(difference.delta.partnerSupportGross)}</div><span>verschil p/m</span></div><div className="result-metric"><div className="stat-label">TOTAAL</div><div className="metric-value">{delta(difference.delta.totalPayments)}</div><span>verschil p/m</span></div></div><div className="notice topgap">{difference.inputChanges.length} gewijzigde invoerwaarde{difference.inputChanges.length === 1 ? "" : "n"}. Engine {current?.engineVersion || "—"} · norm {current?.normVersion || "—"}.</div></section>}

    <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Professionele afwijking</h2><div className="panel-sub">Een override maakt een nieuwe audited calculation snapshot. De bronberekening en eerdere snapshot blijven immutable.</div></div><Link className="btn secondary" href={`/cases/${id}/overrides`}>Alle overrides</Link></div><div className="detail-grid topgap">{overrideOptions.map(([field,label,value]) => <form className="detail-card" action={`/api/cases/${id}/overrides`} method="post" key={field}><input type="hidden" name="field" value={field}/><div className="detail-card-head"><b>{label}</b><span>Engine: {money(value)}</span></div><label className="field topgap"><span>Nieuwe waarde</span><input name="overrideValue" type="number" step="0.01" defaultValue={Number(value) || 0} required/></label><label className="field topgap"><span>Professionele reden</span><textarea name="reason" minLength={10} maxLength={4000} rows={3} required placeholder="Waarom wijkt de professional af van de engine-uitkomst?"/></label><button className="btn topgap" type="submit" disabled={c.reviewStatus === "APPROVED" || c.reviewStatus === "FINAL"}>Opslaan & nieuwe snapshot</button></form>)}</div></section>

    <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Provenance & rapport</h2><div className="panel-sub">De goedkeuring is gekoppeld aan calculation ID, fingerprint, engine en norm.</div></div><a className="btn ghost" href={`/api/cases/${id}/report`} target="_blank" rel="noreferrer">Open rapport</a></div><div className="result-overview"><div className="result-metric"><div className="stat-label">SNAPSHOT</div><div className="metric-value" style={{fontSize:"14px"}}>{current?.id || "—"}</div><span>actuele berekening</span></div><div className="result-metric"><div className="stat-label">FINGERPRINT</div><div className="metric-value" style={{fontSize:"12px"}}>{(result.calculationFingerprint || "—").slice(0,16)}…</div><span>provenance</span></div><div className="result-metric"><div className="stat-label">ENGINE / NORM</div><div className="metric-value" style={{fontSize:"14px"}}>{current?.engineVersion || "—"} / {current?.normVersion || "—"}</div><span>versies</span></div><div className="result-metric"><div className="stat-label">GOEDKEURING</div><div className={`metric-value ${reportProvenanceCurrent ? "green" : ""}`} style={{fontSize:"14px"}}>{reportProvenanceCurrent ? "GEBONDEN" : "NIET GEBONDEN"}</div><span>exacte snapshot</span></div></div></section>

    <div className="two-col topgap"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Workflow</h2><div className="panel-sub">INCOMPLETE → READY_FOR_REVIEW → REVIEWED → APPROVED → FINAL.</div></div><span className="status amber">{c.reviewStatus}</span></div><div className={review.readyForProfessionalReview ? "notice success" : "notice error"}>{review.readyForProfessionalReview ? "Geen kritieke blokkade." : `Los eerst ${review.criticalCount} kritieke punten op.`}</div><div className="actions topgap">{canMarkReady && <form action={`/api/cases/${id}/approval`} method="post"><input type="hidden" name="status" value="READY_FOR_REVIEW"/><button className="btn" type="submit">✓ Klaar voor review</button></form>}{canReview && <form action={`/api/cases/${id}/approval`} method="post"><input type="hidden" name="status" value="REVIEWED"/><button className="btn secondary" type="submit">Markeer REVIEWED</button></form>}{canApprove && <form action={`/api/cases/${id}/approval`} method="post"><input type="hidden" name="status" value="APPROVED"/><button className="btn" type="submit">✓ Goedkeuren</button></form>}{canFinalise && <form action={`/api/cases/${id}/approval`} method="post"><input type="hidden" name="status" value="FINAL"/><button className="btn" type="submit">Maak FINAL</button></form>}{canReopen && <form action={`/api/cases/${id}/approval`} method="post"><input type="hidden" name="status" value="INCOMPLETE"/><button className="btn secondary" type="submit">Heropen review</button></form>}</div></section>
      <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Reviewopmerking</h2><div className="panel-sub">Auditbare professionele toelichting.</div></div></div><form action={`/api/cases/${id}/approval`} method="post" className="topgap"><input type="hidden" name="status" value={c.reviewStatus}/><textarea name="comment" required maxLength={5000} rows={6} placeholder="Bijvoorbeeld: loonstrook gecontroleerd, woonlast onderbouwd, bijzondere kosten beoordeeld en PAL-prioriteit gecontroleerd." style={{width:"100%",boxSizing:"border-box",padding:"12px",borderRadius:"10px",border:"1px solid #d9dee8",fontFamily:"inherit",resize:"vertical"}}/><button className="btn secondary topgap" type="submit">Opslaan in audittrail</button></form></section></div>

    <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Audittrail</h2><div className="panel-sub">Controle, afwijking, herberekening en workflow blijven afzonderlijke gebeurtenissen.</div></div></div>{history.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Datum</th><th>Actie</th><th>Details</th></tr></thead><tbody>{history.slice(0,100).map(x => { const m:any=x.metadata||{}; return <tr key={x.id}><td>{date(x.createdAt)}</td><td><b>{x.action.replace(/^CASE_/, "")}</b></td><td>{m.section ? `${m.section} · snapshot ${String(m.calculationId||"").slice(0,10)}` : m.comment || m.field || (m.reviewScore != null ? `Score ${m.reviewScore}% · ${m.criticalCount || 0} kritieke punten` : "—")}</td></tr>; })}</tbody></table></div> : <div className="empty">Nog geen reviewgebeurtenissen.</div>}</section>
    <div className="topgap notice">{review.disclaimer} APPROVED/FINAL vereist nu zowel een foutvrije automatische review als een compleet professioneel controleformulier op exact dezelfde calculation snapshot.</div>
  </AppShell>;
}
