'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
const money=(v:number)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v)||0);
const n=(v:string)=>Math.max(0,Number(String(v).replace(',','.'))||0);
type Form=Record<string,any>;
const initial:Form={historicalNBGI:'',historicalChildCosts:'',currentChildSupport:'0',currentRecipientNBI:'',currentPayerNBI:'',payerTaxableIncomeAnnual:'',recipientVerdiencapaciteit:'0',recipientOtherIncomeMonthly:'0',recipientAssetsIncomeMonthly:'0',payerAssetsIncomeMonthly:'0',payerHousingCosts:'0',payerMortgageInterestTaxBenefitMonthly:'0',payerOtherNecessaryCosts:'0',payerOtherMaintenance:'0',payerOtherMaintenanceObligations:'0',payerPensionProvisionMonthly:'0',payerCapacityAdjustment:'0',payerBusinessProfitAnnual:'0',payerBusinessProfitYears:'',payerDividendAnnual:'0',payerBox3IncomeAnnual:'0',payerVariableIncomeYears:'',recipientBusinessProfitAnnual:'0',recipientBusinessProfitYears:'',recipientDividendAnnual:'0',recipientBox3IncomeAnnual:'0',payerIsFamily:false,payerOwnHome:false,historicalDate:'',effectiveDate:new Date().toISOString().slice(0,10),useHofnorm:true,concreteNeedNet:'0',incomeComparisonEnabled:false,durationException:'NONE'};
export default function PartnerPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [f,setF]=useState<Form>(initial); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{params.then(async p=>{setId(p.id);try{const r=await fetch(`/api/cases/${p.id}/partneralimentatie`);if(r.ok){const x=await r.json();if(x.suggestedChildSupport)setF((v:any)=>({...v,currentChildSupport:String(x.suggestedChildSupport)}));}}catch{}})},[params]);
 const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v})); const years=(v:string)=>v.split(/[,;\s]+/).filter(Boolean).map(Number).filter((x:number)=>Number.isFinite(x));
 async function calculate(){setBusy(true);setError('');try{const body={...f,historicalNBGI:n(f.historicalNBGI),historicalChildCosts:n(f.historicalChildCosts),currentChildSupport:n(f.currentChildSupport),currentRecipientNBI:n(f.currentRecipientNBI),currentPayerNBI:n(f.currentPayerNBI),payerTaxableIncomeAnnual:n(f.payerTaxableIncomeAnnual),recipientVerdiencapaciteit:n(f.recipientVerdiencapaciteit),recipientOtherIncomeMonthly:n(f.recipientOtherIncomeMonthly),recipientAssetsIncomeMonthly:n(f.recipientAssetsIncomeMonthly),payerAssetsIncomeMonthly:n(f.payerAssetsIncomeMonthly),payerHousingCosts:n(f.payerHousingCosts),payerMortgageInterestTaxBenefitMonthly:n(f.payerMortgageInterestTaxBenefitMonthly),payerOtherNecessaryCosts:n(f.payerOtherNecessaryCosts),payerOtherMaintenance:n(f.payerOtherMaintenance),payerOtherMaintenanceObligations:n(f.payerOtherMaintenanceObligations),payerPensionProvisionMonthly:n(f.payerPensionProvisionMonthly),payerCapacityAdjustment:n(f.payerCapacityAdjustment),payerBusinessProfitAnnual:n(f.payerBusinessProfitAnnual),payerBusinessProfitYears:years(f.payerBusinessProfitYears),payerDividendAnnual:n(f.payerDividendAnnual),payerBox3IncomeAnnual:n(f.payerBox3IncomeAnnual),payerVariableIncomeYears:years(f.payerVariableIncomeYears),recipientBusinessProfitAnnual:n(f.recipientBusinessProfitAnnual),recipientBusinessProfitYears:years(f.recipientBusinessProfitYears),recipientDividendAnnual:n(f.recipientDividendAnnual),recipientBox3IncomeAnnual:n(f.recipientBox3IncomeAnnual),concreteNeedNet:n(f.concreteNeedNet)};const r=await fetch(`/api/cases/${id}/partneralimentatie`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());setResult(await r.json())}catch(e:any){setError(e.message||'Berekening mislukt')}finally{setBusy(false)}}
 const Field=({label,k,help}:{label:string,k:string,help?:string})=><div><label className="label">{label}</label><input className="input" value={f[k]??''} onChange={e=>set(k,e.target.value)}/>{help&&<div className="panel-sub">{help}</div>}</div>;
 return <main className="content" style={{maxWidth:1220}}><div className="page-head"><div><div className="eyebrow">Partneralimentatie · v1.1.1</div><h1 className="page-title">Complexe partneralimentatie</h1><p className="page-subtitle">Professionele berekening met historische behoefte, verdiencapaciteit, ondernemersinkomen, vermogen, eigen woning, onderhoudsverplichtingen en fiscale brutering.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>← Dossier</Link></div></div>
 <section className="panel"><div className="panel-head"><div><h2 className="panel-title">1. Historische behoefte</h2><div className="panel-sub">De hofnorm gebruikt het netto besteedbaar gezinsinkomen rond het uiteengaan minus de kosten van de kinderen.</div></div></div><div className="form-grid topgap"><Field label="Historisch NBGI p/m *" k="historicalNBGI"/><Field label="Kosten kinderen p/m *" k="historicalChildCosts"/><Field label="Datum historisch NBGI" k="historicalDate"/><Field label="Ingangsdatum" k="effectiveDate"/><div className="full"><label className="label"><input type="checkbox" checked={f.useHofnorm} onChange={e=>set('useHofnorm',e.target.checked)}/> Hofnorm gebruiken (60%)</label></div>{!f.useHofnorm&&<Field label="Concrete netto behoefte p/m" k="concreteNeedNet"/>}</div></section>
 <div className="two-col topgap"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">2. Ontvanger</h2><div className="panel-sub">Alle huidige inkomsten en verdiencapaciteit zijn afzonderlijk zichtbaar.</div></div></div><div className="form-grid topgap"><Field label="Huidig NBI p/m" k="currentRecipientNBI"/><Field label="Verdiencapaciteit p/m" k="recipientVerdiencapaciteit"/><Field label="Overig inkomen p/m" k="recipientOtherIncomeMonthly"/><Field label="Inkomen uit vermogen p/m" k="recipientAssetsIncomeMonthly"/><Field label="Winst onderneming p/j" k="recipientBusinessProfitAnnual"/><Field label="Winst onderneming eerdere jaren" k="recipientBusinessProfitYears" help="Komma/ruimte-gescheiden bedragen; gemiddelde wordt gebruikt."/><Field label="Dividend p/j" k="recipientDividendAnnual"/><Field label="Box 3 inkomen p/j" k="recipientBox3IncomeAnnual"/></div></section>
 <section className="panel"><div className="panel-head"><div><h2 className="panel-title">3. Betaler & draagkracht</h2><div className="panel-sub">Ook complexe inkomenscomponenten kunnen worden gescheiden onderbouwd.</div></div></div><div className="form-grid topgap"><Field label="Huidig NBI p/m" k="currentPayerNBI"/><Field label="Belastbaar inkomen p/j" k="payerTaxableIncomeAnnual"/><Field label="Woonlast p/m" k="payerHousingCosts"/><Field label="Hypotheekrente/fiscaal voordeel p/m" k="payerMortgageInterestTaxBenefitMonthly"/><Field label="Bijzondere noodzakelijke lasten p/m" k="payerOtherNecessaryCosts"/><Field label="Pensioen/lijfrentevoorziening p/m" k="payerPensionProvisionMonthly"/><Field label="Andere onderhoudsverplichtingen p/m" k="payerOtherMaintenanceObligations"/><Field label="Correctie draagkracht p/m" k="payerCapacityAdjustment"/><div className="full"><label className="label"><input type="checkbox" checked={f.payerIsFamily} onChange={e=>set('payerIsFamily',e.target.checked)}/> Betaler onderhoudt een gezin — 45%-route controleren</label> <label className="label"><input type="checkbox" checked={f.payerOwnHome} onChange={e=>set('payerOwnHome',e.target.checked)}/> Eigen woning / voormalige echtelijke woning</label></div></div></section></div>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">4. Onderneming, vermogen & variabel inkomen</h2><div className="panel-sub">Gebruik meerdere jaren voor een robuuster beeld. De engine toont deze componenten afzonderlijk zodat een professional ze kan beoordelen.</div></div></div><div className="form-grid topgap"><Field label="Winst onderneming betaler p/j" k="payerBusinessProfitAnnual"/><Field label="Winst onderneming betaler — jaren" k="payerBusinessProfitYears" help="Bijv. 65000 72000 58000"/><Field label="Dividend betaler p/j" k="payerDividendAnnual"/><Field label="Box 3 inkomen betaler p/j" k="payerBox3IncomeAnnual"/><Field label="Variabel inkomen betaler — jaren" k="payerVariableIncomeYears" help="Bijv. 5000 8000 3000"/><Field label="Overig vermogen betaler p/m" k="payerAssetsIncomeMonthly"/></div></section>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">5. Prioriteit, vergelijking & duur</h2><div className="panel-sub">Kinderalimentatie wordt vóór partneralimentatie afgetrokken. Inkomensvergelijking blijft een aanvullende professionele toets.</div></div></div><div className="form-grid topgap"><Field label="Kinderalimentatie p/m" k="currentChildSupport"/><div className="full"><label className="label"><input type="checkbox" checked={f.incomeComparisonEnabled} onChange={e=>set('incomeComparisonEnabled',e.target.checked)}/> Inkomensvergelijking toepassen</label></div><div><label className="label">Duurregel</label><select className="input" value={f.durationException} onChange={e=>set('durationException',e.target.value)}><option value="NONE">Hoofdregel: maximaal 5 jaar</option><option value="CHILD_YOUNGER_THAN_12">Uitzondering: jongste kind &lt; 12 jaar</option><option value="LONG_MARRIAGE_PRE_1970">Overgangsregel lang huwelijk</option><option value="RECEIVER_BORN_1970_OR_EARLIER">Overgangsregel geboortejaar</option><option value="AGREEMENT_OR_COURT">Duur bepaald door afspraak/rechter</option></select></div></div><button className="btn topgap" disabled={busy} onClick={calculate}>{busy?'Berekenen…':'Bereken v1.1.1'}</button>{error&&<div className="notice error topgap">{error}</div>}</section>
 {result&&<section className="panel topgap"><div className="result-hero"><div className="stat-card result-main"><div className="stat-label">BRUTO PARTNERALIMENTATIE</div><div className="stat-value">{money(result.result.monthlyGross)}</div><div className="stat-meta">Netto: {money(result.result.monthlyNet)} p/m · begrenzing: {result.result.limitedBy}</div></div><div className="stat-card"><div className="stat-label">AANVULLENDE BEHOEFTE</div><div className="stat-value">{money(result.need.additionalNeedNet)}</div></div><div className="stat-card"><div className="stat-label">RESTERENDE DRAAGKRACHT</div><div className="stat-value">{money(result.capacity.remainingNet)}</div></div></div><div className="two-col topgap"><div><h2 className="panel-title">Volledige rekenroute</h2>{result.steps.map((s:any)=><div className="summary-line" key={s.step}><span>{s.step}. {s.title}<small style={{display:'block',opacity:.65}}>{s.formula}</small></span><b>{money(s.value)}</b></div>)}</div><div><h2 className="panel-title">Inkomensanalyse</h2>{Object.entries(result.incomeAnalysis).map(([k,v]:any)=><div className="summary-line" key={k}><span>{k}</span><b>{money(v)}</b></div>)}<h2 className="panel-title topgap">Duur</h2><div className="summary-line"><span>Maximum</span><b>{result.duration.maximumYears===null?'Afspraak/rechter':`${result.duration.maximumYears} jaar`}</b></div>{result.warnings.map((w:string,i:number)=><div className="notice topgap" key={i}>• {w}</div>)}</div></div><div className="notice topgap">{result.disclaimer}</div></section>}
 </main>
}
