'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Scenario = any;
const money=(v:any)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v)||0);
export default function ScenariosPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [base,setBase]=useState<any>(null); const [scenarios,setScenarios]=useState<Scenario[]>([]); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [p0,setP0]=useState(''); const [p1,setP1]=useState(''); const [age,setAge]=useState(''); const [childIndex,setChildIndex]=useState('0'); const [busy,setBusy]=useState(false); const [applying,setApplying]=useState(''); const [err,setErr]=useState('');
 const load=async(p:string)=>{const r=await fetch(`/api/cases/${p}`);const c=await r.json();setBase(c);const s=await fetch(`/api/cases/${p}/scenarios`);if(s.ok)setScenarios(await s.json());};
 useEffect(()=>{params.then(p=>{setId(p.id);load(p.id);});},[params]);
 const currentParents=base?.data?.parents||[]; const currentChildren=base?.data?.children||[];
 const baseTotal=Number(base?.result?.transfers?.reduce((s:number,t:any)=>s+Number(t.payment||0),0)||0);
 const create=async()=>{setBusy(true);setErr('');try{const changes:any={parents:{},children:{}};if(p0!=='')changes.parents['0']={nbi:Number(p0.replace(',','.'))};if(p1!=='')changes.parents['1']={nbi:Number(p1.replace(',','.'))};if(age!==''&&currentChildren[Number(childIndex)])changes.children[String(Number(childIndex))]={age:Number(age)};const r=await fetch(`/api/cases/${id}/scenarios`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name||'Nieuw scenario',description,changes})});if(!r.ok)throw new Error(await r.text());const x=await r.json();setScenarios([x,...scenarios]);setName('');setDescription('');setP0('');setP1('');setAge('');}catch(e:any){setErr(e.message||'Opslaan mislukt.')}finally{setBusy(false)}};
 const apply=async(s:any)=>{if(!confirm(`Scenario “${s.name}” definitief maken?\n\nDe huidige berekening wordt vervangen door deze scenario-uitkomst. De huidige berekening blijft als historische snapshot bewaard. De reviewstatus wordt opnieuw op Incompleet gezet.`))return;setApplying(s.id);setErr('');try{const r=await fetch(`/api/cases/${id}/scenarios/${s.id}/apply`,{method:'POST'});if(!r.ok)throw new Error(await r.text());window.location.href=`/cases/${id}`;}catch(e:any){setErr(e.message||'Scenario toepassen mislukt.');setApplying('');}};
 const remove=async(s:any)=>{if(!confirm(`Scenario “${s.name}” verwijderen?`))return;await fetch(`/api/cases/${id}/scenarios/${s.id}`,{method:'DELETE'});setScenarios(xs=>xs.filter(x=>x.id!==s.id));};
 const latest=useMemo(()=>scenarios[0],[scenarios]);
 return <main className="content" style={{maxWidth:1200}}><div className="page-head"><div><div className="eyebrow">Dossier · Scenario's · v1.3.1</div><h1 className="page-title">Scenario & wijzigingen</h1><p className="page-subtitle">Kopieer de actuele berekening conceptueel, wijzig uitgangspunten en maak een scenario desgewenst definitief.</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>← Dossier</Link><Link className="btn secondary" href={`/cases/${id}/history`}>Berekeningshistorie</Link></div></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Nieuw scenario</h2><div className="panel-sub">De basisberekening blijft onveranderd.</div></div></div><div className="form-grid"><div className="full"><label className="label">Naam</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Bijv. inkomen ouder A + €500"/></div><div><label className="label">NBI ouder A</label><input className="input" inputMode="decimal" value={p0} onChange={e=>setP0(e.target.value)} placeholder={String(currentParents[0]?.nbi||'')}/></div><div><label className="label">NBI ouder B</label><input className="input" inputMode="decimal" value={p1} onChange={e=>setP1(e.target.value)} placeholder={String(currentParents[1]?.nbi||'')}/></div><div><label className="label">Kind wijzigen</label><select className="input" value={childIndex} onChange={e=>setChildIndex(e.target.value)}>{currentChildren.map((c:any,i:number)=><option key={i} value={i}>Kind {i+1} · {c.age} jaar</option>)}</select></div><div><label className="label">Nieuwe leeftijd</label><input className="input" type="number" min="0" max="25" value={age} onChange={e=>setAge(e.target.value)} placeholder={String(currentChildren[Number(childIndex)]?.age||'')}/></div><div className="full"><label className="label">Beschrijving</label><textarea className="input" rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Waarom wordt dit scenario doorgerekend?"/></div></div>{err&&<div className="notice error topgap">{err}</div>}<button className="btn topgap" disabled={busy} onClick={create}>{busy?'Scenario wordt berekend…':'Scenario berekenen'}</button></section>
 <aside className="panel"><div className="panel-head"><div><h2 className="panel-title">Basis</h2><div className="panel-sub">Huidige productie-uitkomst</div></div></div><div className="summary-line"><span>Kinderbehoefte</span><b>{money(base?.result?.totalNeed)}</b></div><div className="summary-line"><span>Gezamenlijke draagkracht</span><b>{money(base?.result?.totalCapacity)}</b></div><div className="summary-line"><span>KA-bijdragen</span><b>{money(baseTotal)}</b></div><div className="summary-divider"/><p className="subtle">Een scenario verandert het hoofddossier pas na expliciete bevestiging.</p>{latest&&<div className="notice success topgap">Laatste scenario: <b>{latest.name}</b></div>}</aside></div>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Scenariohistorie</h2><div className="panel-sub">Bekijk, vergelijk, verwijder of maak een scenario definitief.</div></div></div>{scenarios.length===0?<div className="notice">Nog geen scenario's.</div>:<div className="table-wrap"><table className="table"><thead><tr><th>Scenario</th><th>Datum</th><th>KA-behoefte</th><th>Draagkracht</th><th>KA-bijdragen</th><th>Verschil</th><th>Acties</th></tr></thead><tbody>{scenarios.map((s:any)=>{const r=s.result?.child||{};const total=Number(r.transfers?.reduce((a:number,t:any)=>a+Number(t.payment||0),0)||0);return <tr key={s.id}><td><b>{s.name}</b><div className="subtle">{s.description||'—'}</div></td><td>{new Date(s.createdAt).toLocaleString('nl-NL')}</td><td>{money(r.totalNeed)}</td><td>{money(r.totalCapacity)}</td><td>{money(total)}</td><td>{money(total-baseTotal)}</td><td><div className="actions"><button className="btn" disabled={applying===s.id} onClick={()=>apply(s)}>{applying===s.id?'Toepassen…':'Definitief maken'}</button><button className="btn ghost" onClick={()=>remove(s)}>Verwijderen</button></div></td></tr>})}</tbody></table></div>}</section>
 </main>
}
