import Link from "next/link";
import AppShell from "@/components/AppShell";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

const date=(v:any)=>new Intl.DateTimeFormat("nl-NL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const money=(v:any)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v)||0);

export default async function CaseReportPage({params}:{params:Promise<{id:string}>}){
 const u=await requireUser(); const {id}=await params;
 const c=await db.case.findFirst({where:{id,userId:u.id},include:{client:true,calculations:{orderBy:{createdAt:"desc"},take:1},overrides:{select:{id:true}}}});
 if(!c)return <AppShell><div className="notice error">Dossier niet gevonden.</div></AppShell>;
 const calc=c.calculations[0]; const r:any=calc?.result||c.result||{}; const combined=r.combined||{};
 const childTotal=Number(combined.childSupportTotal??(r.transfers||[]).reduce((s:number,t:any)=>s+Number(t.payment||0),0));
 const palGross=Number(combined.partnerSupport?.monthlyGross||r.partnerSupport?.result?.monthlyGross||0);
 const total=Number(combined.totalMonthlyPayments||childTotal+palGross);
 const approved=c.reviewStatus==="APPROVED"||c.reviewStatus==="FINAL";
 const currentSnapshot=!!calc;
 return <AppShell><main className="content report-page" style={{maxWidth:1180}}>
  <div className="page-head report-page-head"><div><div className="eyebrow">Dossier · rapportage</div><h1 className="page-title">Professioneel rapport</h1><p className="page-subtitle">{c.name} · {c.client?.name||"Zonder cliënt"}</p></div><div className="actions"><Link className="btn secondary" href={`/cases/${id}`}>← Dossier</Link><Link className="btn secondary" href={`/cases/${id}/review`}>Reviewcentrum</Link><a className="btn secondary" href={`/api/cases/${id}/report`} target="_blank" rel="noreferrer">Rapportweergave ↗</a><a className="btn" href={`/api/cases/${id}/pdf`}>PDF downloaden</a></div></div>
  <div className={`report-status-card ${approved?"approved":"draft"}`}><div><div className="stat-label">RAPPORTSTATUS</div><h2>{approved?"Gebaseerd op goedgekeurde workflow":"Concept · nog niet goedgekeurd"}</h2><p>{approved?"De rapportage kan worden gebruikt als weergave van de actuele goedgekeurde berekeningssnapshot.":"Controleer de berekening, bronstukken en professionele review voordat je het rapport als definitieve uitkomst gebruikt."}</p></div><span className={`status ${approved?"green":"amber"}`}>{c.reviewStatus}</span></div>
  <section className="result-hero"><div className="stat-card result-main"><div className="stat-label">TOTALE BETALING</div><div className="stat-value">{money(total)}</div><div className="stat-meta">per maand · actuele snapshot</div></div><div className="stat-card"><div className="stat-label">KINDERALIMENTATIE</div><div className="stat-value">{money(childTotal)}</div><div className="stat-meta">per maand</div></div><div className="stat-card"><div className="stat-label">PAL BRUTO</div><div className="stat-value">{money(palGross)}</div><div className="stat-meta">per maand</div></div><div className="stat-card"><div className="stat-label">OVERRIDES</div><div className="stat-value">{c.overrides.length}</div><div className="stat-meta">professionele afwijkingen</div></div></section>
  <section className="panel topgap"><div className="panel-head"><div><div className="section-kicker">Rapportbron</div><h2 className="panel-title">Herleidbaar naar één berekeningssnapshot</h2><div className="panel-sub">De bestaande rapport- en PDF-endpoints gebruiken de actuele geauthenticeerde dossierdata. Deze pagina voegt alleen de professionele rapportage-UX toe.</div></div></div>
   <div className="detail-grid"><div className="detail-card"><div className="detail-card-head"><b>Calculation snapshot</b><span>{currentSnapshot?"Beschikbaar":"Ontbreekt"}</span></div><div className="summary-line"><span>ID</span><b className="mono">{calc?.id||"—"}</b></div><div className="summary-line"><span>Aangemaakt</span><b>{calc?.createdAt?date(calc.createdAt):"—"}</b></div><div className="summary-line"><span>Engine</span><b>{calc?.engineVersion||c.calculationVersion||"—"}</b></div><div className="summary-line"><span>Norm</span><b>{calc?.normVersion||c.normVersionId||"—"}</b></div></div>
   <div className="detail-card"><div className="detail-card-head"><b>Professionele status</b><span className={`status ${approved?"green":"amber"}`}>{c.reviewStatus}</span></div><div className="summary-line"><span>Gereviewd</span><b>{c.reviewedAt?date(c.reviewedAt):"Niet vastgelegd"}</b></div><div className="summary-line"><span>Goedgekeurd</span><b>{c.approvedAt?date(c.approvedAt):"Niet vastgelegd"}</b></div><div className="summary-line"><span>Definitief</span><b>{c.reviewStatus==="FINAL"?"Ja":"Nee"}</b></div></div></div>
  </section>
  <section className="panel topgap"><div className="panel-head"><div><div className="section-kicker">Uitvoer</div><h2 className="panel-title">Rapporteren en controleren</h2></div></div><div className="detail-grid"><div className="detail-card report-action-card"><b>Uitgebreid rapport</b><p className="subtle">Open de bestaande afdrukbare rapportage met uitgangspunten, kinderen, inkomen, draagkracht, PAL, overrides en audit/provenance.</p><a className="btn" href={`/api/cases/${id}/report`} target="_blank" rel="noreferrer">Open rapport ↗</a></div><div className="detail-card report-action-card"><b>PDF</b><p className="subtle">Download de bestaande PDF-uitvoer vanuit de productie PDF-generator.</p><a className="btn" href={`/api/cases/${id}/pdf`}>PDF downloaden</a></div><div className="detail-card report-action-card"><b>Berekeningshistorie</b><p className="subtle">Vergelijk de actuele snapshot met eerdere immutable berekeningen voordat je een rapport deelt.</p><Link className="btn secondary" href={`/cases/${id}/history`}>Historie openen</Link></div><div className="detail-card report-action-card"><b>Audittrail</b><p className="subtle">Controleer review, goedkeuringen, documenten en professionele afwijkingen.</p><Link className="btn secondary" href={`/cases/${id}/activity`}>Audittrail openen</Link></div></div></section>
  <div className="notice topgap">{approved?"De huidige status is goedgekeurd of definitief. Controleer altijd de rapport-provenance in het rapport zelf voordat je het extern gebruikt.":"Dit is een conceptstatus. De rapportage blijft beschikbaar voor controle, maar de workflowstatus is nog niet goedgekeurd."}</div>
 </main></AppShell>;
}
