"use client";
import {useState} from "react";
export default function PrivacyActions({clientId,clientName}:{clientId:string,clientName:string}){
 const [busy,setBusy]=useState(false);
 async function makeLink(){setBusy(true);try{const r=await fetch("/api/privacy/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientId})});if(!r.ok)throw new Error(await r.text());const j=await r.json();await navigator.clipboard.writeText(j.url);alert("Beveiligde cliëntlink gekopieerd. Geldig tot "+new Date(j.expiresAt).toLocaleString("nl-NL"));}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 async function exportOnly(){setBusy(true);try{const r=await fetch(`/api/privacy?clientId=${encodeURIComponent(clientId)}`);if(!r.ok)throw new Error(await r.text());const b=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`alimenta-pro-avg-export-${clientId}.json`;a.click();URL.revokeObjectURL(a.href);}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 async function exportAndDelete(){if(!confirm(`Dit verwijdert ALLE operationele gegevens van ${clientName} na het genereren van de export. Deze actie kan niet ongedaan worden gemaakt. Doorgaan?`))return;setBusy(true);try{const r=await fetch("/api/privacy",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({clientId,confirm:"DELETE"})});if(!r.ok)throw new Error(await r.text());const b=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`alimenta-pro-avg-export-${clientId}.json`;a.click();URL.revokeObjectURL(a.href);location.reload();}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 return <div className="actions"><button className="btn secondary" disabled={busy} onClick={makeLink}>Maak cliëntlink</button><button className="btn secondary" disabled={busy} onClick={exportOnly}>Download gegevens</button><button className="btn danger" disabled={busy} onClick={exportAndDelete}>Download + verwijderen</button></div>
}
