import Link from "next/link";
import { PRICING } from "@/lib/pricing";

const featureItems = [
  ["01", "Één rekenkern", "Berekening, onderbouwing en rapport vertrekken vanuit hetzelfde vastgelegde resultaat."],
  ["02", "Onderbouwing per stap", "Maak invoer, afgeleide bedragen, overrides en bronnen inzichtelijk voor iedere berekening."],
  ["03", "Documenten → inkomen", "Analyseer salarisstroken en jaaropgaven en laat AI alleen controleerbare voorstellen doen."],
  ["04", "Professionele rapporten", "Een strak rapport met samenvatting, financiële analyse en controleerbare rekenbijlage."],
  ["05", "Cliëntwerkplek", "Klantnummer, dossier, documenten, communicatie en archief bij elkaar."],
  ["06", "Controle & audit", "Versies, wijzigingen, rapportmomenten en beheeracties blijven traceerbaar."],
] as const;

export default function Home() {
  return <main className="al-public">
    <header className="al-nav"><div className="al-container" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:24}}><Link href="/" className="al-brand" aria-label="Alimenta Pro home"><span className="al-mark">A</span><span>Alimenta <span style={{color:"var(--al-gold)"}}>PRO</span></span></Link><nav className="al-navlinks" aria-label="Hoofdnavigatie"><Link href="#functionaliteit">Functionaliteit</Link><Link href="#ondernemers">Voor professionals</Link><Link href="#prijzen">Prijzen</Link><Link href="/faq">FAQ</Link></nav><div className="al-nav-actions"><Link href="/login" className="al-btn al-btn-secondary">Inloggen</Link><Link href="/register" className="al-btn al-btn-primary">Account aanmaken</Link></div></div></header>
    <section className="al-hero"><div className="al-container al-hero-grid"><div><div className="al-eyebrow">Professionele alimentatiesoftware</div><h1>Van dossier naar een <span className="al-gradient">onderbouwde uitkomst.</span></h1><p className="al-lead">Alimenta Pro brengt cliënten, berekeningen, documentanalyse en professionele rapportage samen in één rustige werkomgeving voor advocaten, mediators, financieel adviseurs én particulieren.</p><div className="al-actions"><Link href="/register" className="al-btn al-btn-primary">Kies je account →</Link><Link href="/faq" className="al-btn al-btn-secondary">Bekijk juridische FAQ</Link></div><div className="al-proof"><span>Transparante onderbouwing</span><span>Versiehistorie</span><span>Professionele rapportage</span><span>EU-data</span></div></div><div className="al-hero-card"><div className="al-card-inner"><div className="al-card-head"><div><div className="al-card-kicker">Berekening · definitief</div><div className="al-card-title">Kinder- en partneralimentatie</div></div><span className="al-pill">Versie 4</span></div><div className="al-rows"><div className="al-row"><span>Netto besteedbaar inkomen samen</span><strong>€ 6.480 / mnd</strong></div><div className="al-row"><span>Eigen aandeel kosten kinderen</span><strong>€ 1.132 / mnd</strong></div><div className="al-row"><span>Kinderalimentatie</span><strong className="highlight">€ 486 / mnd</strong></div><div className="al-row"><span>Partneralimentatie</span><strong className="highlight">€ 742 / mnd</strong></div></div><div className="al-origin"><div className="al-origin-title">Herkomst van bedragen</div><div className="al-tags"><span className="al-tag">Ingevoerd</span><span className="al-tag">Berekend</span><span className="al-tag gold">Professioneel vastgesteld</span></div><div className="al-card-note">Rekenkern · parameterset · rapport gekoppeld aan versie 4</div></div></div></div></div></section>
    <section id="functionaliteit" className="al-section alt"><div className="al-container"><div className="al-section-head"><div className="al-eyebrow">Functionaliteit</div><h2>Niet alleen het bedrag. Ook het verhaal erachter.</h2><p>De interface is ontworpen rond één centrale vraag: waar komt dit bedrag vandaan?</p></div><div className="al-grid-3">{featureItems.map(([n,title,text])=><article className="al-feature" key={n}><div className="al-feature-num">{n}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="al-section"><div className="al-container"><div className="al-section-head"><div className="al-eyebrow">Werkwijze</div><h2>Een vaste route van intake tot rapport.</h2><p>Rust, overzicht en controle in ieder dossier.</p></div><div className="al-workflow">{[['01','Account kiezen','Particulier of zakelijk. Geen gratis account en geen onduidelijke licenties.'],['02','Dossier opbouwen','Inkomen, wonen, kinderen, zorgverdeling en relevante documenten.'],['03','Berekenen & controleren','Bekijk de onderbouwing, pas gegevens aan en maak een nieuwe versie.'],['04','Rapport uitbrengen','De rapportage hoort exact bij het vastgelegde rekenmoment.']].map(([n,t,p])=><div className="al-step" key={n}><div className="al-step-num">{n}</div><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
    <section id="ondernemers" className="al-section alt"><div className="al-container al-entrepreneur"><div><div className="al-eyebrow">Voor professionals</div><h2 style={{fontSize:'clamp(30px,4vw,45px)',lineHeight:1.08,letterSpacing:'-1.5px'}}>Een cliëntwerkplek die je kunt doorsturen naar advocaat of mediator.</h2><p className="al-lead" style={{fontSize:15,marginTop:18}}>Leg de praktijkidentiteit vast, verzamel documenten, beoordeel AI-voorstellen en lever een professioneel onderbouwd dossier op.</p><ul className="al-list"><li>Cliëntarchief en klantnummer</li><li>Documentcategorieën voor inkomen, wonen en juridisch</li><li>Werkelijke oudernamen in plaats van Ouder A/B</li><li>Geslacht als persoonsgegeven, nooit als rekenfactor</li><li>Audittrail en professionele review</li></ul></div><div className="al-income"><h3>Document → controle → berekening</h3><div className="al-income-line"><span>Salarisstrook / jaaropgave</span><strong>PDF</strong></div><div className="al-income-line"><span>Extractie</span><strong>AI-voorstel</strong></div><div className="al-income-line"><span>Toewijzing</span><strong>Oudernaam</strong></div><div className="al-income-line"><span>Beoordeling</span><strong>Professional</strong></div><div className="al-income-total"><span>Nieuwe snapshot</span><strong>Controleerbaar</strong></div><p className="al-card-note" style={{marginTop:14}}>AI wijzigt nooit zelfstandig een definitieve berekening.</p></div></div></section>
    <section id="prijzen" className="al-section"><div className="al-container"><div className="al-section-head"><div className="al-eyebrow">Prijzen</div><h2>Twee accounts. Geen gratis tussenlaag.</h2><p>Particulier voor één persoonlijk dossier. Zakelijk voor één professionele praktijk.</p></div><div className="al-price-grid">{Object.entries(PRICING).map(([key,p])=><article className={`al-price ${key==='pro'?'featured':''}`} key={key}><div className="al-price-name">{p.name}</div><div className="al-price-amount">€{p.annual.toLocaleString('nl-NL',{minimumFractionDigits:2})}<small> / jaar</small></div><p>{p.description}</p><div className="al-card-note">{p.vatLabel}</div><ul><li>{p.includedClients===1?'1 persoonlijk dossier':`${p.includedClients} actieve cliëntdossiers inbegrepen`}</li><li>Berekeningen en rapportage</li><li>Documenten en audittrail</li></ul><Link href={`/register?type=${key==='private'?'private':'business'}`} className="al-btn al-btn-primary" style={{width:'100%'}}>Kies {p.name}</Link></article>)}</div></div></section>
    <section className="al-section alt"><div className="al-container" style={{textAlign:'center'}}><div className="al-eyebrow">Klaar voor je volgende dossier?</div><h2 style={{fontSize:'clamp(32px,4vw,50px)',letterSpacing:'-1.8px',margin:'16px auto',maxWidth:720}}>Professionele alimentatiesoftware zonder onnodige ruis.</h2><p className="al-lead" style={{margin:'0 auto',fontSize:15}}>Kies Particulier of Zakelijk en ga direct door naar betaling.</p><div className="al-actions" style={{justifyContent:'center'}}><Link href="/register" className="al-btn al-btn-primary">Account kiezen →</Link><Link href="/faq" className="al-btn al-btn-secondary">FAQ</Link></div></div></section>
    <footer className="al-footer"><div className="al-container al-footer-grid"><div>© {new Date().getFullYear()} Alimenta Pro · Professionele software voor alimentatie.</div><div className="al-disclaimer">Alimenta Pro is rekensoftware. De gebruiker blijft verantwoordelijk voor de juridische beoordeling en toepassing van de uitkomsten.</div></div></footer>
  </main>;
}
