import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth"; import { db } from "@/lib/db"; import { calculate } from "@/lib/calculator"; import { calculatePartnerSupport } from "@/lib/partner-engine"; import { caseCreateSchema } from "@/lib/case-validation"; import { calculationFingerprint } from "@/lib/calculation-snapshot"; import { createFamilyContext, familyIdentity } from "@/lib/family-model";
export async function POST(req:Request){try{const u=await requireUser();const parsed=caseCreateSchema.safeParse(await req.json());if(!parsed.success)return new NextResponse("Ongeldige berekeningsinvoer",{status:422});const body=parsed.data;if(body.clientId){const client=await db.client.findFirst({where:{id:body.clientId,userId:u.id}});if(!client)return new NextResponse("Cliënt niet gevonden",{status:404});}
// The external wizard allows GROSS/NET income without a legacy top-level NBI.
// The deterministic calculator keeps a numeric NBI field for its internal contract;
// normalize missing values here without changing the authoritative income profile.
const calculationInput={...body.data,parents:body.data.parents.map(parent=>({...parent,nbi:Number(parent.nbi??0)}))};
const childResult:any=calculate(calculationInput);const childPayments=[0,0];for(const t of childResult.transfers||[]){childPayments[t.payerIndex]+=Number(t.payment||0);}let partnerSupport:any=null;if(body.data.partnerSupport?.enabled){const ps=body.data.partnerSupport;const payerIndex=ps.payerIndex;const recipientIndex=payerIndex===0?1:0;const payer=body.data.parents[payerIndex];const recipient=body.data.parents[recipientIndex];const payerNbi=Number(childResult.incomeResults?.[payerIndex]?.nbiMonthly??payer.nbi)||0;const recipientNbi=Number(childResult.incomeResults?.[recipientIndex]?.nbiMonthly??recipient.nbi)||0;const historicalNBGI=Number(ps.historicalNBGI||body.data.historicalNBGI||0);const historicalChildCosts=Number(ps.historicalChildCosts||childResult.totalNeed||0);const payerHousing=payer.housing;const payerPartner=payer.newPartner;partnerSupport=calculatePartnerSupport({historicalNBGI,historicalChildCosts,currentChildSupport:childPayments[payerIndex],currentRecipientNBI:recipientNbi,currentPayerNBI:payerNbi,payerTaxableIncomeAnnual:Number(ps.payerTaxableIncomeAnnual||payerNbi*12),payerAow:!!payer.aow,payerIsFamily:!!payerPartner?.present&&!(payerPartner.selfSupporting??true),payerHousingCosts:Number(payerHousing?.monthlyCosts||payer.housingCosts||0),payerMortgageInterestTaxBenefitMonthly:Number(ps.payerMortgageInterestTaxBenefitMonthly||payerHousing?.mortgageInterestTaxBenefitMonthly||0),payerMortgagePrincipalMonthly:Number(payerHousing?.mortgagePrincipalMonthly||0),payerOtherNecessaryCosts:Number(payer.specialNecessaryCosts||0),payerOtherMaintenance:Number(payer.otherMaintenance||0),payerOtherMaintenanceObligations:Number(ps.payerOtherMaintenanceObligations||0),payerPensionProvisionMonthly:Number(ps.payerPensionProvisionMonthly||0),payerCapacityAdjustment:Number(payer.capacityAdjustment||0),recipientVerdiencapaciteit:Number(ps.recipientVerdiencapaciteit||0),recipientOtherIncomeMonthly:Number(ps.recipientOtherIncomeMonthly||0),recipientAssetsIncomeMonthly:Number(ps.recipientAssetsIncomeMonthly||0),payerAssetsIncomeMonthly:0,payerOwnHome:payerHousing?.type==="OWNED",incomeComparisonEnabled:!!ps.incomeComparisonEnabled,durationException:ps.durationException||"NONE",useHofnorm:ps.useHofnorm!==false,concreteNeedNet:Number(ps.concreteNeedNet||0),effectiveDate:body.meta?.effectiveDate});}
const childSupportTotal=childPayments.reduce((a,b)=>a+b,0);const partnerPayer=body.data.partnerSupport?.enabled?body.data.partnerSupport.payerIndex:null;const partnerGross=Number(partnerSupport?.result?.monthlyGross||0);const partnerNet=Number(partnerSupport?.result?.monthlyNet||0);const combinedPaymentByParent=[childPayments[0],childPayments[1]];if(partnerPayer!==null)combinedPaymentByParent[partnerPayer]+=partnerGross;const totalMonthlyPayments=combinedPaymentByParent.reduce((a,b)=>a+b,0);const primaryPayerIndex=partnerPayer!==null?partnerPayer:(childPayments[0]>=childPayments[1]?0:1);
// Build one canonical family context for the result/report layer. This prevents
// parent/child names and family context from being lost between wizard steps.
const family=createFamilyContext({
  relationshipStatus: body.data.parents.some(p=>p.newPartner?.present) ? "SEPARATED" : "SEPARATED",
  separationDate: body.meta?.separationDate,
  calculationDate: body.meta?.effectiveDate,
  parentA: { role:"PARENT_A", name: body.data.parents[0].name||"Persoon A" },
  parentB: { role:"PARENT_B", name: body.data.parents[1].name||"Persoon B" },
  children: body.data.children.map((child,index)=>({
    id:`child-${index+1}`,
    name:child.name||`Kind ${index+1}`,
    age:child.age,
    residence:child.residence||"A",
    specialCostsMonthly:child.specialCosts,
    ownIncomeMonthly:child.ownIncome,
    studyGrantMonthly:child.studyGrant,
    studentType:child.studentType,
    livesAtHome:child.livesAtHome,
  })),
  housing:{
    parentA:{type:body.data.parents[0].housing?.type==="OWNED"?"OWN_HOME":body.data.parents[0].housing?.type==="RENT"?"RENT":"OTHER",monthlyCost:body.data.parents[0].housing?.monthlyCosts||body.data.parents[0].housingCosts||0,mortgageInterestMonthly:body.data.parents[0].housing?.mortgageInterestMonthly,mortgagePrincipalMonthly:body.data.parents[0].housing?.mortgagePrincipalMonthly,wozValue:body.data.parents[0].housing?.homeValue},
    parentB:{type:body.data.parents[1].housing?.type==="OWNED"?"OWN_HOME":body.data.parents[1].housing?.type==="RENT"?"RENT":"OTHER",monthlyCost:body.data.parents[1].housing?.monthlyCosts||body.data.parents[1].housingCosts||0,mortgageInterestMonthly:body.data.parents[1].housing?.mortgageInterestMonthly,mortgagePrincipalMonthly:body.data.parents[1].housing?.mortgagePrincipalMonthly,wozValue:body.data.parents[1].housing?.homeValue},
  },
  newPartners:{
    parentA:body.data.parents[0].newPartner?.present?{present:true,name:body.data.parents[0].newPartner.name,relationshipStatus:body.data.parents[0].newPartner.relationship==="MARRIED"?"MARRIED":body.data.parents[0].newPartner.relationship==="REGISTERED_PARTNERSHIP"?"REGISTERED_PARTNERSHIP":body.data.parents[0].newPartner.relationship==="COHABITING_CONTRACT"?"COHABITING_WITH_AGREEMENT":body.data.parents[0].newPartner.relationship==="COHABITING"?"COHABITING_WITHOUT_AGREEMENT":"OTHER",netIncomeMonthly:body.data.parents[0].newPartner.nbiMonthly,children:body.data.parents[0].newPartner.children?.map((c,i)=>({id:`partner-a-child-${i+1}`,name:c.name||`Kind nieuwe partner ${i+1}`,age:c.age,ownIncomeMonthly:c.ownIncome}))}:undefined,
    parentB:body.data.parents[1].newPartner?.present?{present:true,name:body.data.parents[1].newPartner.name,relationshipStatus:body.data.parents[1].newPartner.relationship==="MARRIED"?"MARRIED":body.data.parents[1].newPartner.relationship==="REGISTERED_PARTNERSHIP"?"REGISTERED_PARTNERSHIP":body.data.parents[1].newPartner.relationship==="COHABITING_CONTRACT"?"COHABITING_WITH_AGREEMENT":body.data.parents[1].newPartner.relationship==="COHABITING"?"COHABITING_WITHOUT_AGREEMENT":"OTHER",netIncomeMonthly:body.data.parents[1].newPartner.nbiMonthly,children:body.data.parents[1].newPartner.children?.map((c,i)=>({id:`partner-b-child-${i+1}`,name:c.name||`Kind nieuwe partner ${i+1}`,age:c.age,ownIncomeMonthly:c.ownIncome}))}:undefined,
  },
});
const combinedResult={childSupportTotal,childSupportByParent:childPayments,partnerSupport:partnerSupport?{payerIndex:partnerPayer,recipientIndex:partnerPayer===null?null:partnerPayer===0?1:0,monthlyNet:partnerNet,monthlyGross:partnerGross}:null,combinedPaymentByParent,totalMonthlyPayments,primaryPayerIndex,explanation:[{label:"Totale kinderalimentatie",value:childSupportTotal},{label:"Partneralimentatie netto",value:partnerNet},{label:"Partneralimentatie bruto / betaling",value:partnerGross},{label:"Totale maandelijkse betalingen",value:totalMonthlyPayments}]};const productionResult={...childResult,combined:combinedResult,partnerSupport,family,identity:familyIdentity(family)};const fingerprint=calculationFingerprint(body.data,childResult.engineVersion,childResult.normVersion);const c=await db.case.create({data:{userId:u.id,clientId:body.clientId||null,name:body.name||"Dossier",data:body.data,result:{...productionResult,calculationFingerprint:fingerprint},status:"CALCULATED",calculationVersion:childResult.normVersion,...(body.meta?{metadata:body.meta}:{})}});await db.calculation.create({data:{caseId:c.id,engineVersion:childResult.engineVersion,normVersion:childResult.normVersion,inputSnapshot:body.data,result:{...productionResult,calculationFingerprint:fingerprint}}});await db.auditLog.create({data:{userId:u.id,action:"CASE_CALCULATED",metadata:{caseId:c.id,engineVersion:childResult.engineVersion,normVersion:childResult.normVersion,fingerprint,partnerSupport:!!partnerSupport}}});return NextResponse.json(c);}catch(e:any){return new NextResponse(e?.message||"Berekening mislukt",{status:400});}}