"use client";
import { useEffect, useMemo, useState } from "react";

type Data = any;
const tabs = ["Overzicht", "Klanten", "Abonnementen", "Dossiers", "Mail", "Stripe", "AI", "Systeem", "Audit"];
const plans = ["FREE", "PRO", "PRACTICE", "ENTERPRISE"];
function fmt(value:any){return value?new Date(value).toLocaleString("nl-NL"):"—"}
function Badge({children,tone="gray"}:{children:React.ReactNode;tone?:string}){return <span className={`status ${tone}`}>{children}</span>}
function planName(p:string){return ({FREE:"Free",PRO:"Professional",PRACTICE:"Practice",ENTERPRISE:"Enterprise"} as any)[p]||p}
function mailStatusTone(status:string){return status==="SENT"?"green":"amber"}
export default function AdminPortal({adminEmail}:{adminEmail:string}){
 const [tab,setTab]=useState("Overzicht"),[data,setData]=useState<Data|null>(null),[query,setQuery]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const [mail,setMail]=useState<any>({provider:"POSTMARK",fromName:"",fromEmail:"",replyTo:"",apiKey:"",webhookSecret:""});
 const [ai,setAi]=useState<any>({enabled:false,provider:"OPENAI",model:"",baseUrl:"",apiKey:"",systemPrompt:"",temperature:0.2,maxTokens:4000});
 async function load(){const r=await fetch("/api/beheer-7f3c9a2e/portal",{cache:"no-store"});if(!r.ok){setMsg(await r.text());return}const d=await r.json();setData(d);if(d.config?.mail)setMail((x:any)=>({...x,...d.config.mail}));if(d.config?.ai)setAi((x:any)=>({...x,...d.config.ai}))}
 useEffect(()=>{void load()},[]);
 async function action(payload:any,success="Opgeslagen."){setBusy(true);setMsg("");try{const r=await fetch("/api/beheer-7f3c9a2e/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());setMsg(success);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const users=useMemo(()=> (data?.users||[]).filter((u:any)=>!query||`${u.name||""} ${u.email} ${u.companyName||""}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
 const subscriptionUsers=useMemo(()=>users.filter((u:any)=>u.plan!=="FREE"||u.subscriptionStatus),[users]);
 return <main className="content">
  <div className="page-head"><div><div className="eyebrow">Platform control center</div><h1 className="page-title">Beheerportaal</h1><p className="page-subtitle">Klanten, abonnementen, dossiers, communicatie, AI en productiebeheer op één plek.</p></div><div className="actions"><button className="btn secondary" onClick={()=>void load()} disabled={busy}>↻ Vernieuwen</button><Badge tone="green">Beheer · {adminEmail}</Badge></div></div>
  <div className="admin-tabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {msg&&<div className="notice topgap">{msg}</div>}
  {tab==="Overzicht"&&<><div className="dashboard-grid topgap"><Stat label="Klanten" value={data?.stats?.users??"—"} meta="accounts"/><Stat label="Actieve abonnementen" value={data?.stats?.activeSubscriptions??"—"} meta="active / trialing"/><Stat label="Dossiers" value={data?.stats?.cases??"—"} meta="alle statussen"/><Stat label="Betaalproblemen" value={data?.stats?.pastDue??"—"} meta="past due"/></div><div className="dashboard-grid topgap"><Stat label="Mail verzonden" value={data?.stats?.mailSent??"—"} meta="delivery logs"/><Stat label="Mail mislukt" value={data?.stats?.mailFailed??"—"} meta="delivery failures"/></div><div className="admin-grid-2 topgap"><section className="panel"><Head title="Snelle acties" sub="Veelgebruikte beheerfuncties."/><div className="admin-actions"><Quick onClick={()=>setTab("Klanten")} title="👤 Klanten beheren" sub="Plan, blokkeren, status"/><Quick onClick={()=>setTab("Abonnementen")} title="◆ Abonnementen" sub="Toewijzen en beëindigen"/><Quick onClick={()=>setTab("AI")} title="✦ AI configureren" sub="Provider, model en prompt"/><Quick onClick={()=>setTab("Mail")} title="✉ Mail instellen" sub="Afzender, delivery en failures"/><Quick onClick={()=>setTab("Stripe")} title="$ Stripe" sub="Connectie en webhook"/><Quick onClick={()=>setTab("Systeem")} title="⚙ Systeem" sub="Runtime & readiness"/></div></section><section className="panel"><Head title="Laatste klanten" sub="Recent geregistreerde accounts."/><TableWrap><table className="table"><thead><tr><th>Klant</th><th>Plan</th><th>Status</th><th>Aangemaakt</th></tr></thead><tbody>{(data?.users||[]).slice(0,8).map((u:any)=><tr key={u.id}><td><b>{u.name||u.companyName||"Onbenoemd"}</b><br/><span className="small muted">{u.email}</span></td><td>{planName(u.plan)}</td><td>{u.lockedAt?<Badge tone="amber">Geblokkeerd</Badge>:<Badge tone="green">Actief</Badge>}</td><td>{fmt(u.createdAt)}</td></tr>)}</tbody></table></TableWrap></section></div></>}
  {tab==="Klanten"&&<section className="panel topgap"><Head title="Klantenbeheer" sub="Zoek accounts en beheer toegang, plan en supportstatus."/><input className="input topgap" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoek op naam, e-mail of praktijk…"/><TableWrap><table className="table topgap"><thead><tr><th>Klant</th><th>Plan</th><th>Gebruik</th><th>Abonnement</th><th>Laatste login</th><th>Acties</th></tr></thead><tbody>{users.map((u:any)=><tr key={u.id}><td><b>{u.name||u.companyName||"Onbenoemd"}</b><br/><span className="small muted">{u.email}</span>{u.companyName&&<><br/><span className="small muted">{u.companyName}</span></>}</td><td><select className="select" value={u.plan} onChange={e=>action({action:"setUserPlan",userId:u.id,plan:e.target.value},"Plan aangepast.")} disabled={busy}>{plans.map(p=><option key={p}>{p}</option>)}</select></td><td>{u._count?.clients??0} cliënten · {u._count?.cases??0} dossiers</td><td>{u.subscriptionStatus||"—"}{u.subscriptionEndsAt&&<><br/><span className="small muted">tot {fmt(u.subscriptionEndsAt)}</span></>}</td><td>{fmt(u.lastLoginAt)}</td><td>{u.lockedAt?<button className="btn secondary" onClick={()=>action({action:"unlockUser",userId:u.id},"Account gedeblokkeerd.")}>Deblokkeer</button>:<button className="btn secondary" onClick={()=>action({action:"lockUser",userId:u.id},"Account geblokkeerd.")}>Blokkeer</button>}</td></tr>)}</tbody></table></TableWrap></section>}
  {tab==="Abonnementen"&&<section className="panel topgap"><Head title="Abonnementen & commerciële toegang" sub="Ken een plan toe als supportactie of beëindig een Stripe-subscription."/><div className="notice topgap">Handmatig toegewezen plannen geven direct toegang via het planveld. Stripe-facturatie blijft gekoppeld wanneer een Stripe-subscription aanwezig is.</div><TableWrap><table className="table topgap"><thead><tr><th>Klant</th><th>Plan</th><th>Status</th><th>Stripe</th><th>Acties</th></tr></thead><tbody>{subscriptionUsers.map((u:any)=><tr key={u.id}><td><b>{u.name||u.email}</b><br/><span className="small muted">{u.email}</span></td><td><select className="select" value={u.plan} onChange={e=>action({action:"setUserPlan",userId:u.id,plan:e.target.value},"Abonnementstoegang aangepast.")}><option>FREE</option><option>PRO</option><option>PRACTICE</option><option>ENTERPRISE</option></select></td><td>{u.subscriptionStatus||"—"}</td><td>{u.stripeSubscriptionId?<Badge tone="green">Gekoppeld</Badge>:<Badge>Handmatig</Badge>}</td><td>{u.stripeSubscriptionId&&<button className="btn secondary" onClick={()=>action({action:"cancelSubscription",userId:u.id,atPeriodEnd:true},"Stripe-abonnement wordt aan het einde van de periode beëindigd.")}>Stop per einde periode</button>}</td></tr>)}</tbody></table></TableWrap></section>}
  {tab==="Dossiers"&&<section className="panel topgap"><Head title="Dossiermonitor" sub="Recente berekeningen en reviewstatussen voor support."/><TableWrap><table className="table"><thead><tr><th>Dossier</th><th>Klant</th><th>Account</th><th>Status</th><th>Review</th><th>Bijgewerkt</th></tr></thead><tbody>{(data?.cases||[]).map((c:any)=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.client?.name||"—"}</td><td>{c.user?.name||c.user?.email||"—"}</td><td>{c.status}</td><td>{c.reviewStatus}</td><td>{fmt(c.updatedAt)}</td></tr>)}</tbody></table></TableWrap><div className="notice topgap">Supportinzage is read-only. Het beheerportaal wijzigt geen berekeningsuitkomsten, normversies of review-/approvalstatussen.</div></section>}
  {tab==="Mail"&&<section className="panel topgap"><Head title="Mail & delivery" sub="Providerconfiguratie en operationele bezorgstatussen. Geheimen worden versleuteld opgeslagen en nooit teruggestuurd."/><div className="dashboard-grid topgap"><Stat label="Verzonden" value={data?.stats?.mailSent??"—"} meta="SENT"/><Stat label="Mislukt" value={data?.stats?.mailFailed??"—"} meta="FAILED"/></div><div className="form-grid topgap"><Field label="Provider"><select className="select" value={mail.provider} onChange={e=>setMail({...mail,provider:e.target.value})}><option>POSTMARK</option><option>SMTP</option><option>RESEND</option></select></Field><Field label="Afzendernaam"><input className="input" value={mail.fromName} onChange={e=>setMail({...mail,fromName:e.target.value})} placeholder="Alimenta Pro"/></Field><Field label="Afzender e-mail"><input className="input" type="email" value={mail.fromEmail} onChange={e=>setMail({...mail,fromEmail:e.target.value})} placeholder="noreply@jouwdomein.nl"/></Field><Field label="Reply-to"><input className="input" type="email" value={mail.replyTo} onChange={e=>setMail({...mail,replyTo:e.target.value})} placeholder="support@jouwdomein.nl"/></Field><Field label="API key / token"><input className="input" type="password" value={mail.apiKey} onChange={e=>setMail({...mail,apiKey:e.target.value})} placeholder={mail.configured?"•••••••• (leeg = behouden)":"Provider API key"}/></Field><Field label="Webhook secret"><input className="input" type="password" value={mail.webhookSecret} onChange={e=>setMail({...mail,webhookSecret:e.target.value})} placeholder={mail.webhookConfigured?"•••••••• (leeg = behouden)":"Optioneel"}/></Field></div><div className="actions topgap"><button className="btn" onClick={()=>action({action:"saveMail",...mail},"Mailconfiguratie opgeslagen.")}>Opslaan</button><Badge tone={mail.configured?"green":"amber"}>{mail.configured?"Geconfigureerd":"Nog niet geconfigureerd"}</Badge></div><div className="panel-head topgap"><div><h2 className="panel-title">Recente delivery logs</h2><div className="panel-sub">De laatste 50 mailpogingen, inclusief failures en provider-ID wanneer beschikbaar.</div></div></div><TableWrap><table className="table"><thead><tr><th>Tijd</th><th>Event</th><th>Ontvanger</th><th>Onderwerp</th><th>Status</th><th>Provider-ID</th><th>Fout</th></tr></thead><tbody>{(data?.mailLogs||[]).map((l:any)=><tr key={l.id}><td>{fmt(l.createdAt)}</td><td><b>{l.eventType}</b></td><td className="small">{l.toEmail}</td><td>{l.subject}</td><td><Badge tone={mailStatusTone(l.status)}>{l.status}</Badge></td><td className="small">{l.providerId||"—"}</td><td className="small">{l.error||"—"}</td></tr>)}</tbody></table></TableWrap>{!(data?.mailLogs||[]).length&&<div className="notice topgap">Nog geen transactional mail delivery logs beschikbaar.</div>}</section>}
  {tab==="Stripe"&&<section className="panel topgap"><Head title="Stripe control center" sub="Betaalconfiguratie, status en webhook-informatie."/><div className="dashboard-grid topgap"><Stat label="Status" value={data?.stripe?.configured?"Geconfigureerd":"Ontbreekt"} meta={`modus: ${data?.stripe?.mode||"test"}`}/><Stat label="Webhook" value={data?.stripe?.webhookEndpoint?"Ingesteld":"Ontbreekt"} meta={data?.stripe?.webhookEndpoint||"APP_URL ontbreekt"}/></div><div className="actions topgap"><button className="btn" onClick={()=>action({action:"syncStripe"},"Stripe-verbinding werkt.")}>Stripe-verbinding testen</button><a className="btn secondary" href="/beheer-7f3c9a2e/stripe">Uitgebreid Stripe-beheer →</a></div></section>}
  {tab==="AI"&&<section className="panel topgap"><Head title="AI control center" sub="Centraal bepalen welke AI-provider en welk model gebruikt mag worden."/><div className="notice topgap">AI is ondersteunend. Berekeningen, normatieve uitkomsten en approval blijven deterministisch en verlopen via de bestaande workflows.</div><div className="form-grid topgap"><Field label="AI inschakelen"><label className="toggle-admin"><input type="checkbox" checked={ai.enabled} onChange={e=>setAi({...ai,enabled:e.target.checked})}/> AI-functionaliteit actief</label></Field><Field label="Provider"><select className="select" value={ai.provider} onChange={e=>setAi({...ai,provider:e.target.value})}><option>OPENAI</option><option>AZURE_OPENAI</option><option>ANTHROPIC</option><option>OPENAI_COMPATIBLE</option></select></Field><Field label="Model"><input className="input" value={ai.model} onChange={e=>setAi({...ai,model:e.target.value})} placeholder="bijv. gpt-5.6"/></Field><Field label="Base URL"><input className="input" value={ai.baseUrl} onChange={e=>setAi({...ai,baseUrl:e.target.value})} placeholder="optioneel"/></Field><Field label="API key"><input className="input" type="password" value={ai.apiKey} onChange={e=>setAi({...ai,apiKey:e.target.value})} placeholder={ai.hasKey?"•••••••• (leeg = behouden)":"AI API key"}/></Field><Field label="Temperature"><input className="input" type="number" min="0" max="2" step="0.1" value={ai.temperature} onChange={e=>setAi({...ai,temperature:e.target.value})}/></Field><Field label="Max tokens"><input className="input" type="number" min="256" max="32000" value={ai.maxTokens} onChange={e=>setAi({...ai,maxTokens:e.target.value})}/></Field><Field label="Systeeminstructie" full><textarea className="input" rows={7} value={ai.systemPrompt} onChange={e=>setAi({...ai,systemPrompt:e.target.value})} placeholder="Rol, grenzen en gewenste output…"/></Field></div><button className="btn topgap" onClick={()=>action({action:"saveAi",...ai},"AI-configuratie opgeslagen.")}>AI-configuratie opslaan</button></section>}
  {tab==="Systeem"&&<div className="admin-grid-2 topgap"><section className="panel"><Head title="Productie readiness" sub="Basisconfiguratie."/><Row label="Environment" value={data?.server?.nodeEnv}/><Row label="APP_URL" value={data?.server?.appUrlConfigured?"Geconfigureerd":"Ontbreekt"} tone={data?.server?.appUrlConfigured?"green":"amber"}/><Row label="Session secret" value={data?.server?.sessionConfigured?"Geconfigureerd":"Ontbreekt"} tone={data?.server?.sessionConfigured?"green":"amber"}/><Row label="Stripe" value={data?.stripe?.configured?"Geconfigureerd":"Niet geconfigureerd"} tone={data?.stripe?.configured?"green":"amber"}/><Row label="AI" value={data?.config?.ai?.enabled?"Ingeschakeld":"Uit"}/></section><section className="panel"><Head title="Operationele uitgangspunten" sub="Centrale beheerregels."/><ul className="admin-list"><li>Klanten en toegang beheren</li><li>Abonnementen toewijzen of Stripe beëindigen</li><li>Mail- en AI-secrets versleuteld opslaan</li><li>Beheeracties auditen</li><li>Berekeningen en approval via normale workflows</li><li>Geen secrets teruggeven aan de browser</li></ul></section></div>}
  {tab==="Audit"&&<section className="panel topgap"><Head title="Beheer-auditlog" sub="Recente beveiligings- en beheeracties."/><TableWrap><table className="table"><thead><tr><th>Tijd</th><th>Actie</th><th>Gebruiker</th><th>Metadata</th></tr></thead><tbody>{(data?.logs||[]).map((l:any)=><tr key={l.id}><td>{fmt(l.createdAt)}</td><td><b>{l.action}</b></td><td>{l.userId||"system"}</td><td className="small">{l.metadata?JSON.stringify(l.metadata):"—"}</td></tr>)}</tbody></table></TableWrap></section>}
 </main>
}
function Stat({label,value,meta}:{label:string,value:any,meta?:string}){return <div className="stat-card"><div className="stat-top"><span className="stat-label">{label}</span><span className="stat-icon">●</span></div><div className="stat-value">{value}</div>{meta&&<div className="stat-meta">{meta}</div>}</div>}
function Head({title,sub}:{title:string,sub?:string}){return <div className="panel-head"><div><h2 className="panel-title">{title}</h2>{sub&&<div className="panel-sub">{sub}</div>}</div></div>}
function Field({label,children,full}:{label:string,children:React.ReactNode,full?:boolean}){return <div className={full?"full":""}><label className="label">{label}</label>{children}</div>}
function Row({label,value,tone="gray"}:{label:string,value:any,tone?:string}){return <div className="admin-row"><span>{label}</span><Badge tone={tone}>{value||"—"}</Badge></div>}
function Quick({onClick,title,sub}:{onClick:()=>void,title:string,sub:string}){return <button className="quick-action" onClick={onClick}>{title}<span>{sub}</span></button>}
function TableWrap({children}:{children:React.ReactNode}){return <div className="table-wrap">{children}</div>}
