/**
 * Official source manifest for historical Alimentatienormen.
 *
 * This is a provenance layer only. It does not make a period executable and
 * deliberately contains no reconstructed financial values.
 */

export const RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE =
  "https://www.rechtspraak.nl/voor-advocaten-en-juristen/reglementen-procedures-en-formulieren/civiel/familie-en-jeugdrecht/expertgroep-alimentatienormen";

export type HistoricalNormSource = {
  periodId: string;
  effectiveFrom: string;
  effectiveTo: string;
  sourceTitle: string;
  sourcePage: string;
  parameterDocuments: readonly string[];
  sourceDocumentUrls?: readonly string[];
  transitionNote?: string;
};

export const HISTORICAL_NORM_SOURCE_MANIFEST: readonly HistoricalNormSource[] = [
  {
    periodId: "2006-H1",
    effectiveFrom: "2006-01-01",
    effectiveTo: "2006-06-30",
    sourceTitle: "Bijlage 2006, eerste helft (januari)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Rapport Alimentatienormen 2006", "Bijlage januari 2006", "Kosten van kinderen ten behoeve van vaststelling kinderalimentatie (september 2006)"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/Bijlage-2006-eerste-helft.pdf", "https://www.rechtspraak.nl/SiteCollectionDocuments/rapport-kosten-kkn-sept-2006.pdf"],
    transitionNote: "The January appendix is period-specific. Its exact tables and fiscal parameters still require extraction and independent verification.",
  },
  {
    periodId: "2006-H2",
    effectiveFrom: "2006-07-01",
    effectiveTo: "2006-12-31",
    sourceTitle: "Bijlage 2006, tweede helft (juli)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Rapport Alimentatienormen 2006", "Bijlage juli 2006", "Kosten van kinderen ten behoeve van vaststelling kinderalimentatie (september 2006)"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/Bijlage-2006-tweede-helft.pdf", "https://www.rechtspraak.nl/SiteCollectionDocuments/rapport-kosten-kkn-sept-2006.pdf"],
    transitionNote: "The July appendix is period-specific. Its exact tables and fiscal parameters still require extraction and independent verification.",
  },
  {
    periodId: "2007-H1",
    effectiveFrom: "2007-01-01",
    effectiveTo: "2007-06-30",
    sourceTitle: "Bijlage 2007, eerste helft (januari 2007)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2007 bij het Rapport Alimentatienormen versie september 2006"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/Bijlage-2007-eerste-helft.pdf"],
    transitionNote: "The appendix describes changes effective 1 January 2007, including changes to the child-cost table and income-tax parameters. Parameter extraction is pending.",
  },
  {
    periodId: "2007-H2",
    effectiveFrom: "2007-07-01",
    effectiveTo: "2007-12-31",
    sourceTitle: "Bijlage 2007, tweede helft (juli 2007)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2007 bij het Rapport Alimentatienormen versie september 2006"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/Bijlage-2007-tweede-helft.pdf"],
    transitionNote: "The appendix describes changes effective 1 July 2007, including the minimum-income assistance norms. Parameter extraction is pending.",
  },
  {
    periodId: "2008-H1",
    effectiveFrom: "2008-01-01",
    effectiveTo: "2008-06-30",
    sourceTitle: "Bijlage januari 2008",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2008 bij het Rapport Alimentatienormen versie september 2006"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2008eerstehelft.pdf"],
    transitionNote: "Official appendix describes changes effective 1 January 2008, including tax, child-benefit and ZVW inputs. Full parameter extraction is pending.",
  },
  {
    periodId: "2008-H2",
    effectiveFrom: "2008-07-01",
    effectiveTo: "2008-12-31",
    sourceTitle: "Bijlage juli 2008",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2008 bij het Rapport Alimentatienormen versie september 2006"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2008tweedehelft.pdf"],
    transitionNote: "Official appendix describes changes effective 1 July 2008, including assistance norms and average basic rent. Full parameter extraction is pending.",
  },
  {
    periodId: "2009-H1",
    effectiveFrom: "2009-01-01",
    effectiveTo: "2009-06-30",
    sourceTitle: "Bijlage januari 2009",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2009 bij het Rapport Alimentatienormen versie augustus 2008"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2009eerstehelft.pdf"],
    transitionNote: "Official appendix describes changes effective 1 January 2009, including tax and ZVW inputs and the child-benefit transition. Full parameter extraction is pending.",
  },
  {
    periodId: "2009-H2",
    effectiveFrom: "2009-07-01",
    effectiveTo: "2009-12-31",
    sourceTitle: "Bijlage juli 2009",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2009 bij het Rapport Alimentatienormen versie augustus 2008"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2009tweedehelft.pdf"],
    transitionNote: "Official July appendix is separately published; complete parameter extraction and effective-value verification are pending.",
  },
  {
    periodId: "2010-H1",
    effectiveFrom: "2010-01-01",
    effectiveTo: "2010-06-30",
    sourceTitle: "Bijlage januari 2010",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2010 bij het Rapport Alimentatienormen versie juli 2009"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2010eerstehelft.pdf"],
    transitionNote: "Official appendix describes changes effective 1 January 2010, including tax and ZVW inputs. Full parameter extraction is pending.",
  },
  {
    periodId: "2010-H2",
    effectiveFrom: "2010-07-01",
    effectiveTo: "2010-12-31",
    sourceTitle: "Bijlage juli 2010",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2010 bij het Rapport Alimentatienormen versie juli 2010"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/SiteCollectionDocuments/bijlage2010tweedehelft1.pdf"],
    transitionNote: "Official appendix describes changes effective 1 July 2010, including assistance norms and the Recofa child-support rule. Full parameter extraction is pending.",
  },
  {
    periodId: "2011-H1",
    effectiveFrom: "2011-01-01",
    effectiveTo: "2011-06-30",
    sourceTitle: "2011 first-half period (source document unresolved)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Confirm the applicability of the July 2010 appendix or locate the January 2011 appendix"],
    transitionNote: "The official archive currently lists a second-half 2011 appendix only. This period is catalogued as a provenance gap and remains non-executable.",
  },
  {
    periodId: "2011-H2",
    effectiveFrom: "2011-07-01",
    effectiveTo: "2011-12-31",
    sourceTitle: "Bijlage 2011, tweede helft (juli 2011)",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2011; historical net-method inputs"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1769091122481/content/assets/lbvr/an/lbvr-an-bijlage-2011-tweede-helft.pdf"],
    transitionNote: "The appendix records assistance norms, average basic rent, nominal ZVW, mandatory excess and capacity percentages. The complete period dataset and reference calculations remain pending.",
  },
  {
    periodId: "2012-H1",
    effectiveFrom: "2012-01-01",
    effectiveTo: "2012-06-30",
    sourceTitle: "Bijlage 2012, eerste helft",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage 2012, eerste helft"],
  },
  {
    periodId: "2012-H2",
    effectiveFrom: "2012-07-01",
    effectiveTo: "2012-12-31",
    sourceTitle: "Bijlage 2012, tweede helft",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage 2012, tweede helft"],
  },
  {
    periodId: "2013-H1",
    effectiveFrom: "2013-01-01",
    effectiveTo: "2013-03-31",
    sourceTitle: "Rapport Alimentatienormen versie januari 2013",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Rapport/bijlage 2013-I; January-to-March transition rules"],
    transitionNote: "The official April report describes January–March 2013 as a transition period: new need method and old capacity method. Full parameters remain pending.",
  },
  {
    periodId: "2013-APR",
    effectiveFrom: "2013-04-01",
    effectiveTo: "2013-06-30",
    sourceTitle: "Rapport Alimentatienormen versie april 2013",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Rapport april 2013; Aanpassing richtlijn kinderalimentatie effective 1 April 2013"],
    sourceDocumentUrls: [
      "https://www.rechtspraak.nl/binaries/_rts_1768562463923/content/assets/gharl/rv/gharl-rv-rapport-alimentatienormen-2013.pdf",
      "https://www.rechtspraak.nl/binaries/_rts_1768923224501/content/assets/lbvr/an/lbvr-an-wijziging-16-november-2012-richtlijn.pdf",
    ],
    transitionNote: "The official report says the new child-support calculation method applies from 1 April 2013. Full parameter extraction and validation remain pending.",
  },
  {
    periodId: "2013-H2",
    effectiveFrom: "2013-07-01",
    effectiveTo: "2013-12-31",
    sourceTitle: "Rapport Alimentatienormen, versie juli 2013",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage 2013, tweede helft", "Draagkrachttabel juli 2013"],
  },
  {
    periodId: "2014-H1",
    effectiveFrom: "2014-01-01",
    effectiveTo: "2014-06-30",
    sourceTitle: "Rapport Alimentatienormen, versie januari 2014",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2014", "Bijlage 2014, eerste helft", "Draagkrachttabel 2014"],
  },
  {
    periodId: "2014-H2",
    effectiveFrom: "2014-07-01",
    effectiveTo: "2014-12-31",
    sourceTitle: "Rapport Alimentatienormen, versie juli 2014",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage 2014, tweede helft", "Draagkrachttabel 2014"],
  },
  {
    periodId: "2015-H1",
    effectiveFrom: "2015-01-01",
    effectiveTo: "2015-06-30",
    sourceTitle: "Rapport Alimentatienormen 2015",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2015", "Bijlage 2015, eerste helft", "Draagkrachttabel 2015"],
  },
  {
    periodId: "2015-H2",
    effectiveFrom: "2015-07-01",
    effectiveTo: "2015-12-31",
    sourceTitle: "Rapport Alimentatienormen 2015",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2015", "Bijlage 2015, tweede helft", "Draagkrachttabel 2015"],
  },
  {
    periodId: "2016-H1",
    effectiveFrom: "2016-01-01",
    effectiveTo: "2016-06-30",
    sourceTitle: "Rapport Alimentatienormen 2016",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2016", "Bijlage 2016, eerste helft", "Draagkrachttabel 2016"],
  },
  {
    periodId: "2016-H2",
    effectiveFrom: "2016-07-01",
    effectiveTo: "2016-12-31",
    sourceTitle: "Rapport Alimentatienormen 2016",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2016", "Bijlage 2016, tweede helft", "Draagkrachttabel 2016"],
  },
  {
    periodId: "2017-H1",
    effectiveFrom: "2017-01-01",
    effectiveTo: "2017-06-30",
    sourceTitle: "Rapport Alimentatienormen 2017 januari",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2017", "Bijlage 2017 eerste helft", "Draagkrachttabel 2017"],
  },
  {
    periodId: "2017-H2",
    effectiveFrom: "2017-07-01",
    effectiveTo: "2017-12-31",
    sourceTitle: "Rapport Alimentatienormen 2017",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2017", "Bijlage 2017 tweede helft", "Draagkrachttabel 2017"],
  },
  {
    periodId: "2018-H1",
    effectiveFrom: "2018-01-01",
    effectiveTo: "2018-06-30",
    sourceTitle: "Bijlage januari 2018",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2018; tax, benefit, premium and assistance changes"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1769091278345/content/assets/lbvr/an/lbvr-an-bijlage-2018-eerste-helft.pdf"],
    transitionNote: "The January appendix identifies changes effective 1 January 2018. Full parameter extraction remains pending.",
  },
  {
    periodId: "2018-H2",
    effectiveFrom: "2018-07-01",
    effectiveTo: "2018-12-31",
    sourceTitle: "Bijlage juli 2018",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2018; Participatiewet and assistance norm changes"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1769091279153/content/assets/lbvr/an/lbvr-an-bijlage-2018-tweede-helft.pdf"],
    transitionNote: "The July appendix identifies changes effective 1 July 2018. Full parameter extraction remains pending.",
  },
  {
    periodId: "2019-H1",
    effectiveFrom: "2019-01-01",
    effectiveTo: "2019-06-30",
    sourceTitle: "Bijlage januari 2019",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2019; tax, child benefit, ZVW and assistance parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768837987510/content/assets/rvdr/wa/2019/rvdr-wa-2019-bijlage-2019-eerste-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The January appendix identifies changes effective 1 January 2019. Full parameter extraction remains pending.",
  },
  {
    periodId: "2019-H2",
    effectiveFrom: "2019-07-01",
    effectiveTo: "2019-12-31",
    sourceTitle: "Bijlage juli 2019",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2019; assistance and student-cost norm changes"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768837989522/content/assets/rvdr/wa/2019/rvdr-wa-2019-bijlage-2019-tweede-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The July appendix identifies changes effective 1 July 2019. Full parameter extraction remains pending.",
  },
  {
    periodId: "2020-H1",
    effectiveFrom: "2020-01-01",
    effectiveTo: "2020-06-30",
    sourceTitle: "Rapport Alimentatienormen 2020 januari",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel alimentatie 2020", "Bijlage rapport alimentatienormen versie januari 2020", "Draagkrachttabel alimentatie 2020"],
  },
  {
    periodId: "2020-H2",
    effectiveFrom: "2020-07-01",
    effectiveTo: "2020-12-31",
    sourceTitle: "Rapport Alimentatienormen 2020",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage rapport alimentatienormen versie juli 2020", "Draagkrachttabel alimentatie 2020"],
  },
  {
    periodId: "2021-H1",
    effectiveFrom: "2021-01-01",
    effectiveTo: "2021-06-30",
    sourceTitle: "Bijlage januari 2021",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2021; first-half norm parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838071498/content/assets/rvdr/wa/2021/rvdr-wa-2021-bijlage-2021-eerste-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "Official first-half appendix; complete historical parameter extraction remains pending.",
  },
  {
    periodId: "2021-H2",
    effectiveFrom: "2021-07-01",
    effectiveTo: "2021-12-31",
    sourceTitle: "Bijlage juli 2021",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2021; Participatiewet and assistance norm changes"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838073165/content/assets/rvdr/wa/2021/rvdr-wa-2021-bijlage-2021-tweede-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The July appendix identifies changes effective 1 July 2021. Full parameter extraction remains pending.",
  },
  {
    periodId: "2022-H1",
    effectiveFrom: "2022-01-01",
    effectiveTo: "2022-06-30",
    sourceTitle: "Bijlage januari 2022",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2022; tax, assistance and premium changes"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838104535/content/assets/rvdr/wa/2022/rvdr-wa-2022-bijlage-2022-eerste-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "Official first-half appendix; complete historical parameter extraction remains pending.",
  },
  {
    periodId: "2022-H2",
    effectiveFrom: "2022-07-01",
    effectiveTo: "2022-12-31",
    sourceTitle: "Bijlage juli 2022",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2022; assistance norm change and child-benefit discussion"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838106091/content/assets/rvdr/wa/2022/rvdr-wa-2022-bijlage-2022-tweede-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The July appendix identifies changes effective 1 July 2022. Full parameter extraction remains pending.",
  },
  {
    periodId: "2023-H1",
    effectiveFrom: "2023-01-01",
    effectiveTo: "2023-06-30",
    sourceTitle: "Bijlage januari 2023",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage januari 2023; annual fiscal, benefits and assistance inputs"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838151764/content/assets/rvdr/wa/2023/rvdr-wa-2023-bijlage-2023-eerste-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The existing 2023 records are not period-specific and no 2023 runtime NormSet is integrated; this period remains non-executable until reconciled.",
  },
  {
    periodId: "2023-H2",
    effectiveFrom: "2023-07-01",
    effectiveTo: "2023-12-31",
    sourceTitle: "Bijlage juli 2023",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage juli 2023; second-half norm parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838152841/content/assets/rvdr/wa/2023/rvdr-wa-2023-bijlage-2023-tweede-helft-rapport-alimentatienormen.pdf"],
    transitionNote: "The separate July appendix confirms period-specific source material. Full parameter extraction remains pending.",
  },
  {
    periodId: "2024-H1",
    effectiveFrom: "2024-01-01",
    effectiveTo: "2024-06-30",
    sourceTitle: "Bijlagen rapport Alimentatienormen eerste helft 2024",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlagen januari 2024; current 2024 NormSet and first-half parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838193397/content/assets/rvdr/wa/2024/rvdr-wa-2024-bijlagen-rapport-alimentatienormen-eerste-helft.pdf"],
    transitionNote: "The current 2024 NormSet exists; exact H1/H2 parameter reconciliation and independent reference cases remain required.",
  },
  {
    periodId: "2024-H2",
    effectiveFrom: "2024-07-01",
    effectiveTo: "2024-12-31",
    sourceTitle: "Bijlagen rapport Alimentatienormen tweede helft 2024",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlagen juli 2024; current 2024 NormSet and second-half parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838195483/content/assets/rvdr/wa/2024/rvdr-wa-2024-bijlagen-rapport-alimentatienormen-tweede-helft.pdf"],
    transitionNote: "The second-half appendix uses July tariffs; exact reconciliation and independent reference cases remain required.",
  },
  {
    periodId: "2025-H1",
    effectiveFrom: "2025-01-01",
    effectiveTo: "2025-06-30",
    sourceTitle: "Bijlagen rapport Alimentatienormen eerste helft 2025",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlagen januari 2025; current 2025 NormSet and first-half parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838243183/content/assets/rvdr/wa/2025/rvdr-wa-2025-bijlagen-rapport-alimentatienormen-eerste-helft.pdf"],
    transitionNote: "The current 2025 NormSet exists; exact H1/H2 parameter reconciliation and independent reference cases remain required.",
  },
  {
    periodId: "2025-H2",
    effectiveFrom: "2025-07-01",
    effectiveTo: "2025-12-31",
    sourceTitle: "Bijlagen rapport Alimentatienormen tweede helft 2025",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlagen juli 2025; current 2025 NormSet and second-half parameters"],
    sourceDocumentUrls: ["https://www.rechtspraak.nl/binaries/_rts_1768838245394/content/assets/rvdr/wa/2025/rvdr-wa-2025-bijlagen-rapport-alimentatienormen-tweede-helft.pdf"],
    transitionNote: "The second-half appendix uses July tariffs; exact reconciliation and independent reference cases remain required.",
  },
  {
    periodId: "2026-H1",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-06-30",
    sourceTitle: "Rapport Alimentatienormen januari 2026",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Behoeftetabel 2026", "Bijlage rapport alimentatienormen januari 2026", "Draagkrachttabel alimentatie 2026"],
  },
  {
    periodId: "2026-H2",
    effectiveFrom: "2026-07-01",
    effectiveTo: "2026-12-31",
    sourceTitle: "Rapport Alimentatienormen juli 2026",
    sourcePage: RECHTSPRAAK_ALIMENTATIENORMEN_ARCHIVE,
    parameterDocuments: ["Bijlage rapport alimentatienormen juli 2026", "Draagkrachttabel alimentatie 2026"],
  },
];
