import crypto from 'node:crypto';
const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32Encode(buf: Buffer){let bits=0,v=0,out='';for(const b of buf){v=(v<<8)|b;bits+=8;while(bits>=5){out+=ALPHABET[(v>>>(bits-5))&31];bits-=5}}if(bits)out+=ALPHABET[(v<<(5-bits))&31];return out}
export function base32Decode(input:string){const s=input.replace(/=+$/,'').toUpperCase().replace(/\s/g,'');let bits=0,v=0,out:number[]=[];for(const c of s){const i=ALPHABET.indexOf(c);if(i<0)throw new Error('Ongeldige MFA sleutel');v=(v<<5)|i;bits+=5;if(bits>=8){out.push((v>>>(bits-8))&255);bits-=8}}return Buffer.from(out)}
export function generateSecret(){return base32Encode(crypto.randomBytes(20));}
export function totp(secret:string,time=Date.now()){const key=base32Decode(secret);const counter=Math.floor(time/1000/30);const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',key).update(msg).digest();const o=h[h.length-1]&15;const n=(h.readUInt32BE(o)&0x7fffffff)%1000000;return String(n).padStart(6,'0')}
export function verifyTotp(secret:string,code:string,time=Date.now()){for(let d=-1;d<=1;d++){if(totp(secret,time+d*30000)===code)return true}return false}
export function encryptSecret(secret:string){const key=crypto.createHash('sha256').update(process.env.MFA_ENCRYPTION_KEY||process.env.SESSION_SECRET||'').digest();const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key,iv);const enc=Buffer.concat([c.update(secret,'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${enc.toString('base64url')}`}
export function decryptSecret(blob:string){const key=crypto.createHash('sha256').update(process.env.MFA_ENCRYPTION_KEY||process.env.SESSION_SECRET||'').digest();const [iv,tag,data]=blob.split('.');const d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}
