import Link from "next/link";
import AppShell from "@/components/AppShell";
import {requireUser} from "@/lib/auth";
import {db} from "@/lib/db";

const money=(v:any)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v)||0);
const pct=(v:any)=>`${(Number(v)||0).toFixed(1).replace(".0","")}%`;
const date=(v:any)=>new Intl.DateTimeFormat("nl-NL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));

export default async function CasePage({params}:{params:Promise<{id:string}>}){
 const u=await requireUser(); const {id}=await params;
 const c=await db.case.findFirst({where:{id,userId:u.id},include:{client:true,calculations:{orderBy:{createdAt:"desc"}}}});
 if(!c)return <AppShell><div className="notice error">Dossier niet gevonden.</div></AppShell>;
 const r:any=c.result||{}; const latest=c.calculations[0]; const data:any=c.data||{}; const meta:any=c.metadata||{};
 const childNames=(data.children||[]).map((x:any)=>x.name||"");
 return <AppShell>
  <div className="page-head"><div><div className="eyebrow">Dossier · {c.status} · v1.3.1</div><h1 className="page-title">{c.name}</h1><p className="page-subtitle">{c.client?.name||"Zonder cliënt"} · bijgewerkt {date(c.updatedAt)}</p></div><div className="actions"><Link className="btn secondary" href="/cases">← Dossiers</Link><Link className="btn secondary" href={`/cases/${c.id}/intelligence`}>AI & dossiercontrole</Link><Link className="btn secondary" href={`/cases/${c.id}/review`}>Case Review</Link><Link className="btn secondary" href={`/cases/${c.id}/partneralimentatie`}>Partneralimentatie</Link><Link className="btn secondary" href={`/cases/${c.id}/scenarios`}>Scenario's</Link><Link className="btn secondary" href={`/cases/${c.id}/overrides`}>Professionele overrides</Link><a className="btn secondary" href={`/api/cases/${c.id}/report`} target="_blank" rel="noreferrer">Rapport bekijken</a><Link className="btn" href={`/cases/new?clientId=${c.clientId||""}`}>Nieuwe berekening</Link></div></div>
  <div className="result-hero">
   <div className="stat-card result-main"><div className="stat-label">INDICATIEVE BIJDRAGEBASIS</div><div className="stat-value">{money(r.totalNeed)}</div><div className="stat-meta">Totale behoefte kinderen</div><div className="metric-note">Norm {latest?.normVersion||c.calculationVersion} · engine {latest?.engineVersion||"onbekend"}</div></div>
   <div className="stat-card"><div className="stat-label">DRAAGKRACHT</div><div className="stat-value">{money(r.totalCapacity)}</div><div className="stat-meta">Gezamenlijk</div></div>
   <div className="stat-card"><div className="stat-label">TEKORT</div><div className="stat-value">{money(r.capacityDeficit)}</div><div className="stat-meta">Indicatief</div></div>
   <div className="stat-card"><div className="stat-label">SNAPSHOTS</div><div className="stat-value">{c.calculations.length}</div><div className="stat-meta">Immutable berekeningen</div></div>
  </div>
  <div className="two-col">
   <section className="panel"><div className="panel-head"><div><h2 className="panel-title">Behoefte per kind</h2><div className="panel-sub">Inclusief rekenkundige zorgkorting als afzonderlijke component.</div></div><span className="status green">Berekend</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Kind</th><th>Leeftijd</th><th>Behoefte</th><th>Zorgkorting</th><th>Na zorgkorting</th></tr></thead><tbody>{(r.childResults||[]).map((x:any)=><tr key={x.childIndex}><td>{childNames[x.childIndex-1]||`Kind ${x.childIndex}`}</td><td>{x.age}</td><td>{money(x.need)}</td><td>{money(x.totalCareDiscount)}</td><td><b>{money(Math.max(0, Number(x.need)-Number(x.totalCareDiscount)))}</b></td></tr>)}</tbody></table></div><div className="topgap notice">{r.warning||"Controleer de invoer en de actuele Tremanormen voordat je het resultaat gebruikt."}</div></section>
   <aside className="panel"><div className="panel-head"><div><h2 className="panel-title">Draagkracht ouders</h2><div className="panel-sub">Rekenkundige verdeling van de beschikbare draagkracht.</div></div></div>{(r.parentResults||[]).map((x:any)=><div key={x.parentIndex} className="quick-card"><b>Ouder {x.parentIndex+1}</b><span>NBI {money(x.nbi)} · KGB {money(x.kgb)}</span><div className="progress topgap"><span style={{width:`${Math.min(100,Math.max(0,Number(x.capacity)/(Number(r.totalCapacity)||1)*100))}%`}}/></div><div className="subtle topgap">Draagkracht {money(x.capacity)} · aandeel {pct(x.sharePct)} · indicatieve bijdrage {money(x.indicativeContribution)}</div></div>)}</aside>
  </div>
  <div className="two-col topgap"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Zorgkorting per ouder</h2><div className="panel-sub">Deze waarden zijn rekenkundige uitgangspunten en geen zelfstandig juridisch eindbedrag.</div></div></div>{(r.childResults||[]).map((x:any)=><div className="quick-card" key={`care-${x.childIndex}`}><b>Kind {x.childIndex}</b>{(x.careDiscountByParent||[]).map((amount:any, idx:number)=><div className="summary-line" key={idx}><span>Ouder {idx+1}</span><b>{money(amount)}</b></div>)}</div>)}</section><aside className="panel"><div className="panel-head"><div><h2 className="panel-title">Dossiergegevens</h2><div className="panel-sub">Vastgelegde administratieve metadata.</div></div></div><div className="summary-line"><span>Cliënt</span><b>{c.client?.name||"—"}</b></div><div className="summary-line"><span>Ingangsdatum</span><b>{meta.effectiveDate||"—"}</b></div><div className="summary-line"><span>Normversie</span><b>{latest?.normVersion||c.calculationVersion}</b></div><div className="summary-line"><span>Engineversie</span><b>{latest?.engineVersion||"—"}</b></div>{meta.notes&&<div className="topgap notice">{meta.notes}</div>}</aside></div>
  <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Inkomensanalyse</h2><div className="panel-sub">Transparante route van inkomensgegevens naar het NBI per ouder.</div></div></div><div className="two-col">{(r.incomeResults||[]).map((inc:any, idx:number)=>inc&&<div className="quick-card" key={idx}><b>Ouder {idx+1}</b><div className="summary-line"><span>Bruto jaarinkomen</span><b>{money(inc.grossAnnual)}</b></div><div className="summary-line"><span>Belastbaar box 1</span><b>{money(inc.taxableBox1)}</b></div><div className="summary-line"><span>Belasting vóór kortingen</span><b>{money(inc.taxBeforeCredits)}</b></div><div className="summary-line"><span>Heffingskortingen</span><b>{money(inc.taxCreditTotal)}</b></div><div className="summary-line"><span><strong>NBI p/m</strong></span><b>{money(inc.nbiMonthly)}</b></div>{inc.nbiIncludingKgbMonthly!==inc.nbiMonthly&&<div className="summary-line"><span>NBI incl. KGB p/m</span><b>{money(inc.nbiIncludingKgbMonthly)}</b></div>} {inc.warnings?.length>0&&<div className="notice topgap">{inc.warnings.map((w:string,i:number)=><div key={i}>• {w}</div>)}</div>}</div>)}</div></section>
  <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Indicatieve bijdragen</h2><div className="panel-sub">De motor verwerkt nu ook de netto bijdrage na toepasselijke zorgkorting.</div></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Kind</th><th>Betaler</th><th>Bruto aandeel</th><th>Zorgkorting</th><th>Bijdrage</th></tr></thead><tbody>{(r.transfers||[]).map((t:any)=><tr key={`transfer-${t.childIndex}`}><td>Kind {t.childIndex}</td><td>Ouder {t.payerIndex+1}</td><td>{money(t.grossShare)}</td><td>{money(t.careDiscount)}</td><td><b>{money(t.payment)}</b></td></tr>)}</tbody></table></div></section>
  <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Berekeningshistorie</h2><div className="panel-sub">Elke berekening blijft als snapshot beschikbaar voor controle en vergelijking.</div></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Datum</th><th>Engine</th><th>Norm</th><th>Behoefte</th><th>Draagkracht</th><th>Tekort</th></tr></thead><tbody>{c.calculations.map(x=>{const rr:any=x.result||{};return <tr className="history-row" key={x.id}><td>{date(x.createdAt)}</td><td>{x.engineVersion}</td><td>{x.normVersion}</td><td>{money(rr.totalNeed)}</td><td>{money(rr.totalCapacity)}</td><td>{money(rr.capacityDeficit)}</td></tr>})}</tbody></table></div></section>
 </AppShell>
}
