"use client";
import {useEffect,useState} from "react";

const empty={account:{name:"",email:"",accountType:"BUSINESS",phone:"",addressLine1:"",postalCode:"",city:"",country:"Nederland"},practice:{companyName:"",kvkNumber:"",vatNumber:"",website:"",practiceType:"",billingAddressLine1:"",billingPostalCode:"",billingCity:""},branding:{companyName:"",logoUrl:"",faviconUrl:"",primaryColor:"#1d4ed8",secondaryColor:"#0f172a",accentColor:"#e0f2fe",reportTitle:"",footerText:"",emailFromName:"",emailReplyTo:""}};

export default function SettingsForm(){
 const [form,setForm]=useState<any>(empty); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/settings",{cache:"no-store"}).then(r=>r.json()).then(d=>setForm({...empty,...d,account:{...empty.account,...d.account},practice:{...empty.practice,...d.practice},branding:{...empty.branding,...d.branding}})).catch(()=>setMessage("Instellingen konden niet worden geladen."));},[]);
 const set=(section:string,key:string,value:string)=>setForm((x:any)=>({...x,[section]:{...x[section],[key]:value}}));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(form)});if(!r.ok)throw new Error(await r.text());setMessage("Instellingen opgeslagen.");}catch(e:any){setMessage(e.message||"Opslaan mislukt.");}finally{setBusy(false);}}
 return <>{message&&<div className="notice topgap">{message}</div>}<form onSubmit={save}>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Account</h2><div className="panel-sub">Persoons- en adresgegevens voor je account en facturatie.</div></div></div><div className="form-grid"><Field label="Naam"><input className="input" value={form.account.name} onChange={e=>set("account","name",e.target.value)}/></Field><Field label="E-mailadres"><input className="input" value={form.account.email} disabled/></Field><Field label="Telefoon"><input className="input" value={form.account.phone||""} onChange={e=>set("account","phone",e.target.value)}/></Field><Field label="Land"><input className="input" value={form.account.country||"Nederland"} onChange={e=>set("account","country",e.target.value)}/></Field><Field label="Adres"><input className="input" value={form.account.addressLine1||""} onChange={e=>set("account","addressLine1",e.target.value)}/></Field><Field label="Postcode"><input className="input" value={form.account.postalCode||""} onChange={e=>set("account","postalCode",e.target.value)}/></Field><Field label="Plaats"><input className="input" value={form.account.city||""} onChange={e=>set("account","city",e.target.value)}/></Field></div></section>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Praktijk & facturatie</h2><div className="panel-sub">Deze gegevens worden in de volgende professionele rapport- en factuurgeneratie gebruikt.</div></div></div><div className="form-grid"><Field label="Kantoornaam"><input className="input" value={form.practice.companyName||""} onChange={e=>set("practice","companyName",e.target.value)}/></Field><Field label="Praktijktype"><select className="input" value={form.practice.practiceType||""} onChange={e=>set("practice","practiceType",e.target.value)}><option value="">Kies...</option><option>Advocaat</option><option>Advocatenkantoor</option><option>Mediator</option><option>Financieel adviseur</option><option>Anders</option></select></Field><Field label="KvK-nummer"><input className="input" value={form.practice.kvkNumber||""} onChange={e=>set("practice","kvkNumber",e.target.value)}/></Field><Field label="Btw-id"><input className="input" value={form.practice.vatNumber||""} onChange={e=>set("practice","vatNumber",e.target.value)}/></Field><Field label="Website"><input className="input" value={form.practice.website||""} onChange={e=>set("practice","website",e.target.value)}/></Field><Field label="Factuuradres"><input className="input" value={form.practice.billingAddressLine1||""} onChange={e=>set("practice","billingAddressLine1",e.target.value)}/></Field><Field label="Factuur postcode"><input className="input" value={form.practice.billingPostalCode||""} onChange={e=>set("practice","billingPostalCode",e.target.value)}/></Field><Field label="Factuurplaats"><input className="input" value={form.practice.billingCity||""} onChange={e=>set("practice","billingCity",e.target.value)}/></Field></div></section>
 <section className="panel topgap"><div className="panel-head"><div><h2 className="panel-title">Logo, huisstijl & rapport</h2><div className="panel-sub">De ingestelde identiteit wordt de bron voor professionele rapportage in update 2.</div></div></div><div className="form-grid"><Field label="Logo URL"><input className="input" value={form.branding.logoUrl||""} onChange={e=>set("branding","logoUrl",e.target.value)} placeholder="https://..."/></Field><Field label="Rapporttitel"><input className="input" value={form.branding.reportTitle||""} onChange={e=>set("branding","reportTitle",e.target.value)}/></Field><Field label="Afzendernaam e-mail"><input className="input" value={form.branding.emailFromName||""} onChange={e=>set("branding","emailFromName",e.target.value)}/></Field><Field label="Reply-to"><input className="input" value={form.branding.emailReplyTo||""} onChange={e=>set("branding","emailReplyTo",e.target.value)}/></Field><Field label="Footer rapport"><textarea className="input" rows={4} value={form.branding.footerText||""} onChange={e=>set("branding","footerText",e.target.value)}/></Field><Field label="Bedrijfsnaam op rapport"><input className="input" value={form.branding.companyName||""} onChange={e=>set("branding","companyName",e.target.value)}/></Field></div></section>
 <div className="actions topgap"><button className="btn" disabled={busy}>{busy?"Opslaan…":"Instellingen opslaan"}</button><span className="muted">Accounttype: {form.account.accountType === "PRIVATE" ? "Particulier" : "Zakelijk"}</span></div></form></>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="field-label">{label}</span>{children}</label>}
