import {requireUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {PRICING,priceForClients} from "@/lib/pricing";

const euro=(v:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(v);
const statusLabel=(v:string|undefined)=>({ACTIVE:"Actief",TRIALING:"Proefperiode",PAST_DUE:"Betaling vereist",CANCELED:"Opgezegd",INCOMPLETE:"Incompleet"}[String(v)]||"Geen actief abonnement");
const planLabel=(v:string)=>v==="PRIVATE"?"Particulier":v==="PRO"?"Zakelijk":"Geen actief abonnement";
const features:Record<string,string[]>={
 private:["1 persoonlijk dossier","KA/PAL berekeningen","Documenten en professionele review","Professionele rapportage","Audittrail en berekeningshistorie"],
 pro:["5 actieve cliëntdossiers inbegrepen","Extra dossiercapaciteit kan door beheer worden toegekend","Volledige alimentatieberekeningen","Professionele rapportage","Audit trail en berekeningshistorie"]
};
export default async function Billing(){
 const u=await requireUser();
 const [clients,cases,calculations]=await Promise.all([db.client.count({where:{userId:u.id,status:"ACTIVE"}}),db.case.count({where:{userId:u.id}}),db.calculation.count({where:{case:{userId:u.id}}})]);
 const active=!!u.stripeSubscriptionId&&["ACTIVE","TRIALING","PAST_DUE"].includes(String(u.subscriptionStatus));
 return <main className="container"><div className="billing-hero"><div><div className="eyebrow">Account · abonnement</div><h1 className="page-title">Eenvoudige abonnementen, professionele functies.</h1><p className="page-subtitle">Geen gratis plan. Betaling hoort bij registratie en je account heeft daarna één duidelijke productroute.</p></div><div className="billing-current"><span>Huidig abonnement</span><b>{planLabel(String(u.plan))}</b><small>{statusLabel(u.subscriptionStatus??undefined)}</small></div></div><div className="billing-usage"><div className="usage-item"><span>Actieve cliënten</span><b>{clients}</b></div><div className="usage-item"><span>Dossiers</span><b>{cases}</b></div><div className="usage-item"><span>Berekeningen</span><b>{calculations}</b></div></div><div className="billing-grid topgap">{Object.entries(PRICING).map(([k,p])=>{const current=(k==="private"&&u.plan==="PRIVATE")||(k==="pro"&&u.plan==="PRO");return <section className={`billing-card ${k==="pro"?"featured":""}`} key={k}>{k==="pro"&&<span className="billing-badge">Zakelijk</span>}<h2>{p.name}</h2><p className="desc">{p.description}</p><div className="billing-price">{euro(p.annual)}<small> / jaar</small></div><div className="billing-annual">{p.vatLabel}</div><ul className="billing-features">{features[k].map(f=><li key={f}>{f}</li>)}</ul>{current?<button className="btn secondary" disabled>Huidig abonnement</button>:active?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Beheren via Stripe</button></form>:<form action="/api/stripe/checkout" method="post"><input type="hidden" name="plan" value={p.key}/><button className="btn" type="submit">Kies {p.name} →</button></form>}</section>})}</div><div className="billing-bottom"><div className="billing-info"><h3>Abonnement en facturen beheren</h3><p>Via het beveiligde Stripe-klantportaal kun je betaalmethode en facturen beheren.</p>{u.stripeCustomerId?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Open klantportaal →</button></form>:<p className="topgap">Nog geen betaalprofiel gekoppeld.</p>}</div><div className="billing-info"><h3>Extra zakelijke dossiercapaciteit</h3><p>De zakelijke licentie start met 5 actieve cliëntdossiers. Extra capaciteit wordt als beheer-entitlement toegevoegd; er komt geen tweede business-plan naast.</p></div></div><div className="notice topgap">Stripe Price IDs moeten door de beheerder aan <b>private</b> en <b>pro</b> worden gekoppeld voordat live betalingen kunnen plaatsvinden.</div></main>
}
