import {requireUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {PRICING,priceForClients} from "@/lib/pricing";

const euro=(v:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(v);
const statusLabel=(v:string|undefined)=>({ACTIVE:"Actief",TRIALING:"Proefperiode",PAST_DUE:"Betaling vereist",CANCELED:"Opgezegd",INCOMPLETE:"Incompleet"}[String(v)]||"Geen actief abonnement");
const planLabel=(v:string)=>({pro:"Professional",practice20:"Practice 20",practice50:"Practice 50",enterprise:"Enterprise"}[String(v)]||String(v||"Geen plan"));
const features:Record<string,string[]>={
 pro:["5 actieve cliëntdossiers inbegrepen","Extra cliëntdossier: €19,95 per jaar","Volledige alimentatieberekeningen","Uitgebreide professionele rapporten","Audit trail en berekeningshistorie"],
 practice20:["20 actieve cliëntdossiers inbegrepen","Geen toeslag per extra cliënt","Volledige alimentatieberekeningen","Uitgebreide professionele rapporten","Audit trail en berekeningshistorie"],
 practice50:["50 actieve cliëntdossiers inbegrepen","Geen toeslag per extra cliënt","Volledige alimentatieberekeningen","Uitgebreide professionele rapporten","Audit trail en berekeningshistorie"],
 enterprise:["Onbeperkt aantal cliëntdossiers","Meerdere gebruikers","Volledige alimentatieberekeningen","Uitgebreide professionele rapporten","Maatwerk en enterprise-inrichting"]
};
export default async function Billing(){
 const u=await requireUser();
 const [clients,cases,calculations]=await Promise.all([db.client.count({where:{userId:u.id,status:"ACTIVE"}}),db.case.count({where:{userId:u.id}}),db.calculation.count({where:{case:{userId:u.id}}})]);
 const active=!!u.stripeSubscriptionId&&["ACTIVE","TRIALING","PAST_DUE"].includes(String(u.subscriptionStatus));
 return <main className="container"><div className="billing-hero"><div><div className="eyebrow">Account · abonnement</div><h1 className="page-title">Kies de ruimte die bij je praktijk past.</h1><p className="page-subtitle">Transparante jaarprijzen, duidelijke dossierlimieten en één plek voor facturen en betaalgegevens.</p></div><div className="billing-current"><span>Huidig abonnement</span><b>{planLabel(u.plan)}</b><small>{statusLabel(u.subscriptionStatus)}</small></div></div>
 <div className="billing-usage"><div className="usage-item"><span>Actieve cliënten</span><b>{clients}</b></div><div className="usage-item"><span>Dossiers</span><b>{cases}</b></div><div className="usage-item"><span>Berekeningen</span><b>{calculations}</b></div></div>
 <div className="billing-grid topgap">{Object.entries(PRICING).map(([k,p])=>{const current=String(u.plan).toLowerCase()===k;const estimated=priceForClients(k as keyof typeof PRICING,clients);const monthly=estimated/12;return <section className={`billing-card ${k==="practice20"?"featured":""}`} key={k}>{k==="practice20"&&<span className="billing-badge">Meest gekozen</span>}<h2>{p.name}</h2><p className="desc">{p.description}</p><div className="billing-price">{euro(p.annual)}<small> / jaar</small></div><div className="billing-annual">ongeveer {euro(monthly)} per maand · excl. btw indien van toepassing</div><ul className="billing-features">{features[k].map(f=><li key={f}>{f}</li>)}</ul>{k==="pro"&&<div className="billing-annual">Bij {clients} actieve cliënten: circa {euro(estimated)} per jaar.</div>}{current?<button className="btn secondary" disabled>Huidig abonnement</button>:active?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Wijzigen via Stripe</button></form>:<form action="/api/stripe/checkout" method="post"><input type="hidden" name="plan" value={k}/><button className="btn" type="submit">Kies {p.name} →</button></form>}</section>})}</div>
 <div className="billing-bottom"><div className="billing-info"><h3>Abonnement en facturen beheren</h3><p>Via het beveiligde Stripe-klantportaal kun je je abonnement, facturen en betaalmethode beheren. Een wijziging van plan wordt daar verwerkt.</p>{u.stripeCustomerId?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Open klantportaal →</button></form>:<p className="topgap">Er is nog geen Stripe-klant gekoppeld. Kies eerst een abonnement.</p>}</div><div className="billing-info"><h3>Hoe werkt de dossierlimiet?</h3><p>De limiet gaat over actieve cliëntdossiers. Professional bevat 5 dossiers; Practice 20 en 50 bevatten respectievelijk 20 en 50 dossiers. Enterprise is ingericht voor onbeperkt gebruik.</p><p className="topgap">Je berekeningen en rapporten blijven onderdeel van je dossier en worden niet per plan anders berekend.</p></div></div>
 <div className="notice topgap">Stripe moet door de beheerder aan de juiste Price IDs worden gekoppeld voordat betalingen in productie kunnen plaatsvinden. De bedragen hierboven zijn de Alimenta Pro-prijsconfiguratie; btw-behandeling en facturatiegegevens worden door Stripe afgehandeld.</div>
 </main>
}
