import {requireUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {PRICING} from "@/lib/pricing";

const euro=(v:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(v);
const statusLabel=(v:string|undefined)=>({ACTIVE:"Actief",TRIALING:"Proefperiode",PAST_DUE:"Betaling vereist",CANCELED:"Opgezegd",INCOMPLETE:"Incompleet"}[String(v)]||"Geen actief abonnement");
const planLabel=(v:string)=>v==="PRIVATE"?"Particulier":v==="PRO"?"Zakelijk":"Geen actief abonnement";
const features:Record<string,string[]>={
  private:["1 persoonlijk dossier","KA/PAL-berekeningen","Documenten en professionele review","Professionele rapportage","Audittrail en berekeningshistorie"],
  pro:["5 actieve cliëntdossiers inbegrepen","Extra dossiercapaciteit via beheer","Volledige alimentatieberekeningen","Professionele rapportage","Audittrail en berekeningshistorie"]
};

export default async function Billing(){
  const u=await requireUser();
  const [clients,cases,calculations]=await Promise.all([
    db.client.count({where:{userId:u.id,status:"ACTIVE"}}),
    db.case.count({where:{userId:u.id}}),
    db.calculation.count({where:{case:{userId:u.id}}})
  ]);
  const active=!!u.stripeSubscriptionId&&["ACTIVE","TRIALING","PAST_DUE"].includes(String(u.subscriptionStatus));

  return <main className="content billing-page">
    <style>{`\n      .billing-page{max-width:1400px}\n      .billing-hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;margin-bottom:22px}\n      .billing-current{min-width:220px;padding:18px;background:#fff;border:1px solid var(--line);border-radius:14px}\n      .billing-current span,.billing-current small{display:block;color:var(--muted);font-size:11px}\n      .billing-current b{display:block;color:var(--ink);font-size:20px;margin:5px 0}\n      .billing-usage{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:18px}\n      .usage-item{background:#fff;border:1px solid var(--line);border-radius:14px;padding:17px}\n      .usage-item span{display:block;color:var(--muted);font-size:11px}\n      .usage-item b{display:block;color:var(--ink);font-size:27px;margin-top:7px}\n      .billing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}\n      .billing-card{position:relative;display:flex;flex-direction:column;background:#fff;border:1px solid var(--line);border-radius:14px;padding:24px;min-width:0}\n      .billing-card.featured{border:2px solid var(--blue);padding:23px}\n      .billing-card h2{margin:0;color:var(--ink);font-size:21px}\n      .billing-card .desc{color:var(--muted);font-size:12px;min-height:36px}\n      .billing-price{color:var(--ink);font-size:32px;font-weight:800;margin-top:12px}\n      .billing-price small{font-size:12px;font-weight:500;color:var(--muted)}\n      .billing-annual{color:var(--muted);font-size:11px;margin-top:4px}\n      .billing-features{padding-left:20px;color:var(--ink);font-size:12px;line-height:1.9;flex:1;margin:20px 0}\n      .billing-badge{position:absolute;right:20px;top:20px;background:var(--blue-soft);color:var(--blue);font-size:10px;font-weight:800;padding:5px 9px;border-radius:999px}\n      .billing-bottom{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:18px}\n      .billing-info{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px}\n      .billing-info h3{color:var(--ink);font-size:15px;margin:0 0 8px}\n      .billing-info p{color:var(--muted);font-size:12px;line-height:1.6}\n      @media(max-width:760px){.billing-hero{display:block}.billing-current{margin-top:18px}.billing-usage,.billing-grid,.billing-bottom{grid-template-columns:1fr}.billing-card,.billing-card.featured{padding:20px}.billing-card.featured{padding:19px}}\n    `}</style>
    <div className="billing-hero"><div><div className="eyebrow">Account · abonnement</div><h1 className="page-title">Eenvoudige abonnementen, professionele functies.</h1><p className="page-subtitle">Beheer je plan, gebruik en facturatie vanuit dezelfde vertrouwde Alimenta-omgeving.</p></div><div className="billing-current"><span>Huidig abonnement</span><b>{planLabel(String(u.plan))}</b><small>{statusLabel(u.subscriptionStatus??undefined)}</small></div></div>
    <div className="billing-usage"><div className="usage-item"><span>Actieve cliënten</span><b>{clients}</b></div><div className="usage-item"><span>Dossiers</span><b>{cases}</b></div><div className="usage-item"><span>Berekeningen</span><b>{calculations}</b></div></div>
    <div className="billing-grid topgap">{Object.entries(PRICING).map(([k,p])=>{const current=(k==="private"&&u.plan==="PRIVATE")||(k==="pro"&&u.plan==="PRO");return <section className={`billing-card ${k==="pro"?"featured":""}`} key={k}>{k==="pro"&&<span className="billing-badge">Zakelijk</span>}<h2>{p.name}</h2><p className="desc">{p.description}</p><div className="billing-price">{euro(p.annual)}<small> / jaar</small></div><div className="billing-annual">{p.vatLabel}</div><ul className="billing-features">{features[k].map(f=><li key={f}>{f}</li>)}</ul>{current?<button className="btn secondary" disabled>Huidig abonnement</button>:active?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Beheren via Stripe</button></form>:<form action="/api/stripe/checkout" method="post"><input type="hidden" name="plan" value={p.key}/><button className="btn" type="submit">Kies {p.name} →</button></form>}</section>})}</div>
    <div className="billing-bottom"><div className="billing-info"><h3>Abonnement en facturen beheren</h3><p>Via het beveiligde Stripe-klantportaal kun je je betaalmethode en facturen beheren.</p>{u.stripeCustomerId?<form action="/api/stripe/portal" method="post"><button className="btn secondary" type="submit">Open klantportaal →</button></form>:<p className="topgap">Nog geen betaalprofiel gekoppeld.</p>}</div><div className="billing-info"><h3>Extra zakelijke dossiercapaciteit</h3><p>De zakelijke licentie start met 5 actieve cliëntdossiers. Extra capaciteit wordt als beheer-entitlement toegevoegd; er komt geen tweede business-plan naast.</p></div></div>
    <div className="notice topgap">Stripe Price IDs moeten door de beheerder aan <b>private</b> en <b>pro</b> worden gekoppeld voordat live betalingen kunnen plaatsvinden.</div>
  </main>;
}
