"use client";
import Link from "next/link";import {Suspense,useRef,useState} from "react";import {useSearchParams} from "next/navigation";
function ScanPageContent(){const params=useSearchParams();const video=useRef<HTMLVideoElement>(null);const canvas=useRef<HTMLCanvasElement>(null);const [stream,setStream]=useState<MediaStream|null>(null);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [clientId,setClientId]=useState(params.get("clientId")||"");const [caseId,setCaseId]=useState(params.get("caseId")||"");
 async function start(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});setStream(s);if(video.current)video.current.srcObject=s;}catch{setMsg("Camera kon niet worden gestart. Gebruik de knop Bestand kiezen als alternatief.")}}
 function stop(){stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 async function capture(){if(!video.current||!canvas.current)return;const w=video.current.videoWidth,h=video.current.videoHeight;canvas.current.width=w;canvas.current.height=h;canvas.current.getContext("2d")?.drawImage(video.current,0,0,w,h);canvas.current.toBlob(async b=>{if(b)await upload(new File([b],`scan-${Date.now()}.jpg`,{type:"image/jpeg"}))},"image/jpeg",.92)}
 async function upload(file:File){setBusy(true);setMsg("");try{const fd=new FormData();fd.append("file",file);if(clientId)fd.append("clientId",clientId);if(caseId)fd.append("caseId",caseId);const r=await fetch("/api/documents/upload",{method:"POST",body:fd});if(!r.ok)throw new Error(await r.text());const j=await r.json();setMsg(`Document opgeslagen: ${j.name}. Je kunt het daarna vanuit het dossier met AI laten analyseren.`);}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="content mobile-scan"><div className="page-head"><div><div className="eyebrow">Documenten</div><h1 className="page-title">Scan & importeer</h1><p className="page-subtitle">Gebruik je telefoon of tablet als documentscanner. Maak een foto van een loonstrook, jaaropgave of andere relevante stukken.</p></div><Link className="btn secondary" href="/dashboard">← Terug</Link></div><section className="panel"><div className="form-grid"><div><label className="label">Cliënt-ID (optioneel)</label><input className="input" value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="Plak cliënt-ID"/></div><div><label className="label">Dossier-ID (optioneel)</label><input className="input" value={caseId} onChange={e=>setCaseId(e.target.value)} placeholder="Plak dossier-ID"/></div></div><div className="scan-frame topgap"><video ref={video} autoPlay playsInline muted/><div className="scan-guide">Plaats het document binnen het kader</div></div><canvas ref={canvas} hidden/><div className="actions topgap"><button className="btn" onClick={stream?capture:start} disabled={busy}>{stream?"Maak scan":"Start camera"}</button>{stream&&<button className="btn secondary" onClick={stop}>Camera stoppen</button>}<label className="btn secondary">Bestand kiezen<input hidden type="file" accept="image/*,.pdf" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div>{msg&&<div className="notice topgap">{msg}</div>}<div className="notice success topgap"><b>AI-verwerking.</b> Na upload blijft het document in jouw beveiligde omgeving. AI-analyse is een aparte, controleerbare stap en kan centraal worden uitgeschakeld.</div></section></main>}
export default function ScanPage(){return <Suspense fallback={<main className="content"><div className="panel"><p className="muted">Scanner laden…</p></div></main>}><ScanPageContent/></Suspense>}
