import Link from "next/link";
import AppShell from "@/components/AppShell";
import DemoStarter from "@/components/DemoStarter";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

function euro(v:any){return new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v)||0)}
const reviewLabel=(v:string)=>v==="FINAL"?"Definitief":v==="APPROVED"?"Goedgekeurd":v==="REVIEWED"?"Gereviewd":v==="READY_FOR_REVIEW"?"Klaar voor review":"Te controleren";
const reviewClass=(v:string)=>v==="FINAL"||v==="APPROVED"?"green":v==="REVIEWED"||v==="READY_FOR_REVIEW"?"amber":"gray";

export default async function Dashboard(){
 const user=await requireUser();
 const [clients,cases,calcs,readyCount,reviewedCount,incompleteCount,documentCount,proposedFactCount,openTaskCount]=await Promise.all([
  db.client.count({where:{userId:user.id,status:"ACTIVE"}}),
  db.case.findMany({where:{userId:user.id},orderBy:{updatedAt:"desc"},take:12,include:{client:true}}),
  db.calculation.count({where:{case:{userId:user.id}}}),
  db.case.count({where:{userId:user.id,reviewStatus:"READY_FOR_REVIEW"}}),
  db.case.count({where:{userId:user.id,reviewStatus:"REVIEWED"}}),
  db.case.count({where:{userId:user.id,reviewStatus:"INCOMPLETE"}}),
  db.document.count({where:{userId:user.id}}),
  db.incomeFact.count({where:{userId:user.id,status:"PROPOSED"}}),
  db.task.count({where:{userId:user.id,status:"OPEN"}}),
 ]);
 const latest=cases[0]; const result:any=latest?.result||{};
 const workQueue=cases.filter(c=>c.reviewStatus!=="FINAL"&&c.reviewStatus!=="APPROVED").slice(0,6);
 return <AppShell><div className="page-head"><div><div className="eyebrow">Overzicht</div><h1 className="page-title">Goedemorgen, {user.name?.split(" ")[0] || "welkom"}.</h1><p className="page-subtitle">Hier vind je de actuele stand van je cliënten, dossiers en berekeningen.</p></div><div className="actions"><Link className="btn secondary" href="/clients/new">+ Cliënt</Link><Link className="btn" href="/cases/new">Nieuwe berekening <span>→</span></Link></div></div>
 <div className="panel topgap"><div className="panel-head"><div><div className="section-kicker">Demo-modus</div><h2 className="panel-title">In één klik een volledig testdossier</h2><div className="panel-sub">Ideaal om de hele keten te testen zonder handmatig alle wizardvelden in te vullen.</div></div><span className="status green">FICTIEF</span></div><DemoStarter/></div>
 <div className="dashboard-grid"><div className="stat-card"><div className="stat-top"><span className="stat-label">ACTIEVE CLIËNTEN</span><span className="stat-icon">●</span></div><div className="stat-value">{clients}</div><div className="stat-meta">Eigen cliënten in je praktijk</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">DOSSIERS</span><span className="stat-icon">□</span></div><div className="stat-value">{cases.length}</div><div className="stat-meta">Recente dossiers in beeld</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">DOCUMENTEN</span><span className="stat-icon">▤</span></div><div className="stat-value">{documentCount}</div><div className="stat-meta">Veilig opgeslagen dossierdocumenten</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">AI-VOORSTELLEN</span><span className="stat-icon">✦</span></div><div className="stat-value">{proposedFactCount}</div><div className="stat-meta">Feiten die professionele beoordeling vragen</div></div></div>
 <div className="dashboard-grid topgap"><div className="stat-card"><div className="stat-label">BEREKENINGEN</div><div className="stat-value">{calcs}</div><div className="stat-meta">Opgeslagen rekenmomenten</div></div><div className="stat-card"><div className="stat-label">OPEN TAKEN</div><div className="stat-value">{openTaskCount}</div><div className="stat-meta">Professionele opvolging die nog openstaat</div></div><div className="stat-card"><div className="stat-label">ABONNEMENT</div><div className="stat-value" style={{fontSize:20}}>{user.plan}</div><div className="stat-meta">{user.subscriptionStatus || "Geen actief abonnement"}</div></div></div>
 <section className="panel topgap"><div className="panel-head"><div><div className="section-kicker">Werkvoorraad</div><h2 className="panel-title">Wat vraagt vandaag aandacht?</h2><div className="panel-sub">Naast berekeningsreviews worden AI-voorstellen en open taken als aparte professionele werkstromen zichtbaar gemaakt.</div></div><Link className="btn ghost" href="/cases">Alle dossiers</Link></div><div className="dashboard-grid"><Link className="stat-card" href="/cases?review=READY_FOR_REVIEW"><div className="stat-label">KLAAR VOOR REVIEW</div><div className="stat-value">{readyCount}</div><div className="stat-meta">Open de professionele review</div></Link><Link className="stat-card" href="/cases?review=REVIEWED"><div className="stat-label">NA REVIEW</div><div className="stat-value">{reviewedCount}</div><div className="stat-meta">Klaar voor goedkeuring</div></Link><Link className="stat-card" href="/cases?review=INCOMPLETE"><div className="stat-label">AANDACHT NODIG</div><div className="stat-value">{incompleteCount}</div><div className="stat-meta">Nog niet klaar voor review</div></Link><Link className="stat-card" href="/cases"><div className="stat-label">AI-FACT REVIEW</div><div className="stat-value">{proposedFactCount}</div><div className="stat-meta">Open een dossier om voorstellen te beoordelen</div></Link><Link className="stat-card" href="/tasks"><div className="stat-label">OPEN TAKEN</div><div className="stat-value">{openTaskCount}</div><div className="stat-meta">Bekijk professionele opvolging</div></Link></div>{workQueue.length===0?<div className="empty topgap">Geen open werkvoorraad. Alle recente dossiers zijn goedgekeurd of definitief.</div>:<div className="table-wrap topgap"><table className="table"><thead><tr><th>Dossier</th><th>Cliënt</th><th>Status</th><th>Bijgewerkt</th><th></th></tr></thead><tbody>{workQueue.map(c=><tr key={c.id}><td><Link className="table-link" href={`/cases/${c.id}`}>{c.name}</Link></td><td>{c.client?.name||"—"}</td><td><span className={`status ${reviewClass(c.reviewStatus)}`}>{reviewLabel(c.reviewStatus)}</span></td><td>{new Intl.DateTimeFormat("nl-NL",{day:"2-digit",month:"short",year:"numeric"}).format(c.updatedAt)}</td><td><Link className="btn ghost" href={`/cases/${c.id}/workflow`}>Open workflow →</Link></td></tr>)}</tbody></table></div>}</section>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Recente dossiers</h2><div className="panel-sub">Je laatst gewijzigde dossiers</div></div><Link className="btn ghost" href="/cases/new">Nieuw dossier</Link></div>{cases.length===0?<div className="empty">Nog geen dossiers. Maak je eerste berekening aan.</div>:<table className="table"><thead><tr><th>Dossier</th><th>Cliënt</th><th>Status</th><th>Bijgewerkt</th><th></th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><Link className="table-link" href={`/cases/${c.id}`}>{c.name}</Link></td><td>{c.client?.name||"—"}</td><td><span className={`status ${reviewClass(c.reviewStatus)}`}>{reviewLabel(c.reviewStatus)}</span></td><td>{new Intl.DateTimeFormat("nl-NL",{day:"2-digit",month:"short"}).format(c.updatedAt)}</td><td><Link href={`/cases/${c.id}`} className="table-link">Open →</Link></td></tr>)}</tbody></table>}</section>
 <aside className="panel"><div className="panel-head"><div><h2 className="panel-title">Snel starten</h2><div className="panel-sub">Veelgebruikte acties</div></div></div><Link href="/cases/new" className="quick-card"><b>Nieuwe alimentatieberekening</b><span>Start een nieuw dossier en leg de uitgangspunten vast.</span></Link><Link href="/clients/new" className="quick-card"><b>Nieuwe cliënt toevoegen</b><span>Maak een cliënt aan en koppel later één of meerdere dossiers.</span></Link><Link href="/billing" className="quick-card"><b>Abonnement beheren</b><span>Bekijk je plan, facturatie en betaalmethode.</span></Link>{latest&&<div className="topgap"><div className="stat-label">LAATSTE RESULTAAT</div><div style={{fontFamily:"Manrope",fontSize:23,fontWeight:800,marginTop:7}}>{euro(result.totalNeed)}</div><div className="stat-meta">Behoefte · {latest.name}</div></div>}</aside></div>
 </AppShell>
}