import Link from "next/link";
import AppShell from "@/components/AppShell";
import DemoStarter from "@/components/DemoStarter";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

function euro(v:any){return new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v)||0)}
export default async function Dashboard(){
 const user=await requireUser();
 const [clients,cases,calcs]=await Promise.all([
  db.client.count({where:{userId:user.id,status:"ACTIVE"}}),
  db.case.findMany({where:{userId:user.id},orderBy:{updatedAt:"desc"},take:8,include:{client:true}}),
  db.calculation.count({where:{case:{userId:user.id}}})
 ]);
 const latest=cases[0]; const result:any=latest?.result||{};
 return <AppShell><div className="page-head"><div><div className="eyebrow">Overzicht</div><h1 className="page-title">Goedemorgen, {user.name?.split(" ")[0] || "welkom"}.</h1><p className="page-subtitle">Hier vind je de actuele stand van je cliënten, dossiers en berekeningen.</p></div><div className="actions"><Link className="btn secondary" href="/clients/new">+ Cliënt</Link><Link className="btn" href="/cases/new">Nieuwe berekening <span>→</span></Link></div></div>
 <div className="panel topgap"><div className="panel-head"><div><div className="section-kicker">Demo-modus</div><h2 className="panel-title">In één klik een volledig testdossier</h2><div className="panel-sub">Ideaal om de hele keten te testen zonder handmatig alle wizardvelden in te vullen.</div></div><span className="status green">FICTIEF</span></div><DemoStarter/></div>
 <div className="dashboard-grid"><div className="stat-card"><div className="stat-top"><span className="stat-label">ACTIEVE CLIËNTEN</span><span className="stat-icon">●</span></div><div className="stat-value">{clients}</div><div className="stat-meta">Eigen cliënten in je praktijk</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">DOSSIERS</span><span className="stat-icon">□</span></div><div className="stat-value">{cases.length}</div><div className="stat-meta">Recente dossiers in beeld</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">BEREKENINGEN</span><span className="stat-icon">✓</span></div><div className="stat-value">{calcs}</div><div className="stat-meta">Opgeslagen rekenmomenten</div></div><div className="stat-card"><div className="stat-top"><span className="stat-label">ABONNEMENT</span><span className="stat-icon">€</span></div><div className="stat-value" style={{fontSize:20}}>{user.plan}</div><div className="stat-meta">{user.subscriptionStatus || "Geen actief abonnement"}</div></div></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h2 className="panel-title">Recente dossiers</h2><div className="panel-sub">Je laatst gewijzigde dossiers</div></div><Link className="btn ghost" href="/cases/new">Nieuw dossier</Link></div>{cases.length===0?<div className="empty">Nog geen dossiers. Maak je eerste berekening aan.</div>:<table className="table"><thead><tr><th>Dossier</th><th>Cliënt</th><th>Status</th><th>Bijgewerkt</th><th></th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><Link className="table-link" href={`/cases/${c.id}`}>{c.name}</Link></td><td>{c.client?.name||"—"}</td><td><span className={`status ${c.status==="CALCULATED"?"green":c.status==="DRAFT"?"amber":"gray"}`}>{c.status==="CALCULATED"?"Berekend":c.status==="DRAFT"?"Concept":"Gearchiveerd"}</span></td><td>{new Intl.DateTimeFormat("nl-NL",{day:"2-digit",month:"short"}).format(c.updatedAt)}</td><td><Link href={`/cases/${c.id}`} className="table-link">Open →</Link></td></tr>)}</tbody></table>}</section>
 <aside className="panel"><div className="panel-head"><div><h2 className="panel-title">Snel starten</h2><div className="panel-sub">Veelgebruikte acties</div></div></div><Link href="/cases/new" className="quick-card"><b>Nieuwe alimentatieberekening</b><span>Start een nieuw dossier en leg de uitgangspunten vast.</span></Link><Link href="/clients/new" className="quick-card"><b>Nieuwe cliënt toevoegen</b><span>Maak een cliënt aan en koppel later één of meerdere dossiers.</span></Link><Link href="/billing" className="quick-card"><b>Abonnement beheren</b><span>Bekijk je plan, facturatie en betaalmethode.</span></Link>{latest&&<div className="topgap"><div className="stat-label">LAATSTE RESULTAAT</div><div style={{fontFamily:"Manrope",fontSize:23,fontWeight:800,marginTop:7}}>{euro(result.totalNeed)}</div><div className="stat-meta">Behoefte · {latest.name}</div></div>}</aside></div>
 </AppShell>
}
