import Link from "next/link";

const faq=[
 ["Hoe wordt kinderalimentatie berekend?","Alimenta volgt de gekozen normset en legt behoefte, draagkracht, zorgkorting, verdeling en eventuele correcties afzonderlijk vast. De uitkomst is rekensoftware en geen automatisch juridisch oordeel."],
 ["Wat is netto besteedbaar inkomen (NBI)?","Het NBI is het inkomen dat volgens de gebruikte alimentatiemethodiek beschikbaar is na relevante fiscale en inkomenscomponenten. Welke posten meetellen wordt per normjaar en dossier onderbouwd."],
 ["Hoe wordt de behoefte van een kind bepaald?","Voor minderjarige kinderen wordt de behoefte in beginsel bepaald aan de hand van de toepasselijke behoefte-tabellen en het relevante gezinsinkomen. Voor 18- tot 21-jarigen gelden andere uitgangspunten."],
 ["Hoe wordt draagkracht berekend?","Draagkracht wordt bepaald vanuit het relevante inkomen en de noodzakelijke lasten volgens de toepasselijke draagkrachtformule en tabellen. De gebruikte parameters worden aan het rekenmoment gekoppeld."],
 ["Wat is zorgkorting?","Zorgkorting is een vermindering die samenhangt met de zorg die een ouder voor de kinderen draagt. De exacte korting hangt af van de zorgregeling en de toepasselijke norm."],
 ["Hoe wordt het kindgebonden budget verwerkt?","Het kindgebonden budget kan onderdeel zijn van de berekening van de behoefte en/of draagkracht, afhankelijk van de gebruikte methodiek. Alimenta toont de verwerking expliciet zodat een professional die kan controleren."],
 ["Hoe wordt partneralimentatie berekend?","Partneralimentatie kent een behoeftefase en een draagkrachtfase. De toepassing van de Hofnorm, aanvullende behoefte, draagkracht en prioriteit van kinderalimentatie wordt afzonderlijk zichtbaar gemaakt."],
 ["Heeft een nieuwe partner invloed op de berekening?","Een nieuwe partner kan onder omstandigheden relevant zijn voor de draagkracht- en gezinscontext. Alimenta vraagt alleen de gegevens die voor de gekozen route relevant zijn en legt professionele keuzes vast."],
 ["Hoe worden andere kinderen en onderhoudsverplichtingen verwerkt?","Andere onderhoudsverplichtingen kunnen de beschikbare draagkracht beïnvloeden. Deze verplichtingen worden als afzonderlijke invoer behandeld en niet stilzwijgend in een ander bedrag verstopt."],
 ["Kan een rechter van de alimentatienormen afwijken?","Ja. De aanbevelingen van de Expertgroep Alimentatienormen zijn geen wet. In een individuele zaak kan een rechter of partij gemotiveerd van de aanbevelingen afwijken. Daarom bevat ieder rapport ruimte voor aannames, waarschuwingen en professionele overrides."],
] as const;

export default function FaqPage(){return <main className="al-public"><header className="al-nav"><div className="al-container" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:24}}><Link href="/" className="al-brand"><span className="al-mark">A</span><span>Alimenta <span style={{color:"var(--al-gold)"}}>PRO</span></span></Link><div className="al-nav-actions"><Link href="/login" className="al-btn al-btn-secondary">Inloggen</Link><Link href="/register" className="al-btn al-btn-primary">Account aanmaken</Link></div></div></header><section className="al-section"><div className="al-container" style={{maxWidth:900}}><div className="al-eyebrow">Kennis & juridische context</div><h1 style={{fontSize:"clamp(38px,6vw,64px)",lineHeight:1.03,letterSpacing:"-2px"}}>10 vragen over KA, PAL en de rekenregels.</h1><p className="al-lead">Deze antwoorden leggen uit wat Alimenta berekent en waarom bepaalde gegevens worden gevraagd. Ze vervangen geen juridische beoordeling.</p><div style={{display:"grid",gap:14,marginTop:40}}>{faq.map(([q,a],i)=><details key={q} className="al-feature" open={i===0}><summary style={{cursor:"pointer",fontWeight:800,fontSize:18}}>{i+1}. {q}</summary><p style={{marginTop:14}}>{a}</p></details>)}</div><div className="al-actions" style={{marginTop:36}}><Link href="/register" className="al-btn al-btn-primary">Bekijk de abonnementen →</Link><Link href="/" className="al-btn al-btn-secondary">Terug naar home</Link></div></div></section><footer className="al-footer"><div className="al-container al-footer-grid"><div>© {new Date().getFullYear()} Alimenta Pro</div><div className="al-disclaimer">Alimenta Pro is rekensoftware. De gebruiker blijft verantwoordelijk voor de juridische beoordeling en toepassing van de uitkomsten.</div></div></footer></main>}
